### ISSUE TITLE
Report result with same command is not constant 

### ISSUE THREAD

**Issue by JustinWonjaePark** [tern-tools/tern#1002]
**Describe the bug**
When you run tern with Scancode extension repeatedly, 
small parts of the results are different from each other.
![image](https://user-images.githubusercontent.com/33045921/125573635-e1b9d043-8039-4a65-b5fb-b76a14cd075a.png)
![image](https://user-images.githubusercontent.com/33045921/125573721-44864046-51bf-4b97-881a-e2705f341af7.png)
![image](https://user-images.githubusercontent.com/33045921/125573815-61b3e37b-9b12-4b15-968f-a2ebc0489da1.png)

**To Reproduce**
1. pull fossology/fossology:3.10.0
2. Run command `tern report -f json -x scancode -i debian:buster -o debian_buster_img_scancode.json`

**Error in terminal**
no error occurred

**Expected behavior**
The report on a same docker image should be same.

**Environment you are running Tern on**
Tern at commit 273e3c8
Python 3.6.13
Docker version 19.03.13, build 4484c46d9d

Distributor ID: Ubuntu
Description: Ubuntu 16.04.7 LTS
Release: 16.04
Codename: xenial

**Comment by rnjudge** [comment]
Thanks for the issue @JustinWonjaePark -- Is the parts of the code that are differing file-related output from Scancode or package metadata from Tern?

**Comment by rnjudge** [comment]
Can you also confirm which version of scancode you have installed?

**Comment by JustinWonjaePark** [comment]
Hello @rnjudge , I am sorry for late response.
The version of scancode that I use is 21.3.31

**Comment by JustinWonjaePark** [comment]
@rnjudge , it actually looks part that returned from Scancode.
(copyright and license information by files)

**Comment by rnjudge** [comment]
@JustinWonjaePark it looks like this is an issue with scancode then? or is it specific to Tern? Tern simply captures scancode output and reports on it. Are the differences you're seeing after back to back runs on the same image or running with a fresh cache for the same image? I can try to reproduce but a little confused by your steps that say to pull fossology image and then run a tern+scancode report for debian:buster. Can you clarify what you did to produce this error?

**Comment by rnjudge** [comment]
Here are the steps to run scancode without Tern:

1) `tern -k report -i debian:buster`. The `-k` option keeps the containers mounted filesystem so you can run scancode on it independently of Tern.
2) Find the mounted filesystem by running`ls ~/.tern/temp/`. The directory under `~/temp` for me and the debian:buster image was `e63992559353a522e62a73bc137fd023ee97e1226b96947df8e00e73d1a9d627`. Whatever the directory there is, use that.
3) Run scancode on the mounted filesystem. `sudo /home/rjudge/ternenv/bin/scancode -ilpcu --quiet --timeout 300 -n 4 --json - /home/rjudge/.tern/temp/e63992559353a522e62a73bc137fd023ee97e1226b96947df8e00e73d1a9d627/contents`

The output of scancode will print directly to the terminal.

**Comment by rnjudge** [comment]
Hi @JustinWonjaePark any followup from your investigation?
