### ISSUE TITLE
To make the commit message part a bit more clear

### ISSUE THREAD

**Issue by sayantani11** [tern-tools/tern#1019]
**Description**
The part of 'commit message format' part can be a bit confusing for new contributors as most people try to do it with github rather than git.

**Implementation**
Would like to make a small change in the CONTRIBUTING.md file, adding the steps they need to follow for the commit message before pushing the changes

**Comment by sayantani11** [comment]
Can I do it? It's like a very small change

**Comment by rnjudge** [comment]
@sayantani11 go for it!

**Comment by sayantani11** [comment]
@rnjudge Can we close this issue now?
