### ISSUE TITLE
Change SPDX tag value package download location from NONE to NOASSERTION

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#1038]
**Describe the issue**
Tern currently reports the package download location in SPDX reports as `NONE` In the recent SPDX DocFest, it was discussed that the value should actually be `NOASSERTION`.

**To Reproduce**
1. Run `tern report -i <image> -f spdxtagvalue
2. See `PackageDownloadLocation` is `NONE` for packages
```
PackageName: layer.tar
SPDXID: SPDXRef-3205b843ce
PackageFileName: 992b336a125fb51fdb4508dedde569038ddd1263a3c39daaf71d41bbfcab0698/layer.tar
PackageDownloadLocation: NONE
```

**Expected behavior**
`PackageDownloadLocation` should be `NOASSERTION` for packages

**To fix**
Make changes to `tern/formats/spdx/spdxtagvalue/layer_helpers.py`and `tern/formats/spdx/spdxtagvalue/package_helpers.py` to change `PackageDownloadLocation` value to `NOASSERTION`

**Comment by jayeritz** [comment]
I can take this one
