### ISSUE TITLE
Direct check for key in command_lib['base'] dictionary

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#1040]
**WARNING**
If this is your first tern contribution, please update your local git settings using [these instructions](https://github.com/nishakm/puns#how-to-configure-your-git).

DO NOT USE THE GITHUB UI!

When creating your commit message for your PR, make sure to use `git commit -s` rather than `git commit -m`

Remember to add a `Fixes: #1040` line in your commit message.

**Description**
The get_base_listing function checks if a specific key exists
in the command_lib['base'] dictionary. Rather than checking the
return value of command_lib['base'].keys() we directly check the
command_lib['base'] dictionary to improve performance.

**Implementation**
Make the following change in `tern/analyze/default/command_lib/command_lib.py`:
```
 57 def get_base_listing(key):                                                      
 58     '''Given the key listing in base.yml, return the dictionary'''              
 59     listing = {}                                                                
 60     if key in command_lib['base'].keys(): <--- change this to command_lib['base']                                       
 61         listing = copy.deepcopy(command_lib['base'][key])                       
 62     else:                                                                       
 63         logger.warning("%s", errors.no_listing_for_base_key.format(             
 64             listing_key=key))                                                   
 65     return listing  
```

**Comment by debbie-leung** [comment]
I'd like to work on this issue.
