### ISSUE TITLE
Direct check for key in command_lib['snippets'] dictionary

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#1041]
**WARNING**
If this is your first tern contribution, please update your local git settings using [these instructions](https://github.com/nishakm/puns#how-to-configure-your-git).

DO NOT USE THE GITHUB UI!

When creating your commit message for your PR, make sure to use `git commit -s` rather than `git commit -m`

Remember to add a `Fixes: #1041` line in your commit message.

**Description**
The get_command_listing function checks if a specific command
name exists in the command_lib['snippets'] dictionary. Rather than
checking the return value of command_lib['snippets'].keys() we directly 
check the command_lib['snippets'] dictionary to improve performance.

**Implementation**
Make the following change in `tern/analyze/default/command_lib/command_lib.py`:
```
 68 def get_command_listing(command_name):                                          
 69     '''Given a command name retrieve the listing if it exists'''                
 70     listing = {}                                                                
 71     if command_name in command_lib['snippets'].keys(): <-- change this to command_lib['snippets']               
 72         listing = command_lib['snippets'][command_name]                         
 73     else:                                                                       
 74         logger.warning("%s", errors.no_listing_for_snippet_key.format(          
 75             listing_key=command_name))                                          
 76     return listing     
```

**Comment by Samaiya** [comment]
@nishakm can you please assign this to me , I am participating in vGHC OSD event

**Comment by Samaiya** [comment]
@nishakm what is the upstream branch to use for this ?
