### ISSUE TITLE
ScanCode should run with n-1 cores, instead of using all available resources

### ISSUE THREAD

**Issue by maxhbr** [tern-tools/tern#1062]
AFAIK it is recommended to run ScanCode with with one less core than is available. So it would be probably better to replace

https://github.com/tern-tools/tern/blob/87e7cdd154bc3cad98db1174b192ab9592adcffb/tern/extensions/scancode/executor.py#L139

by

```python
command = "scancode -ilpcu --quiet --timeout 300 -n {} --json -".format(processes - 1) 
```

**Comment by pombredanne** [comment]
@maxhbr ScanCode is happy to use it all, but it typically helps to use one less core to avoid saturating the CPU: this way it leaves some CPU cycles for the user. For instance on my laptop which is a quad core with 8 threads, I typically run with `-n7`.
