### ISSUE TITLE
Tern doesn't detect the license for packages found in layer

### ISSUE THREAD

**Issue by Raghavendrakamatagi-eng** [tern-tools/tern#1074]
**Describe the bug**
Tern doesn't detect the license for packages found in layer

**Error in terminal"
No license found for packages

**Expected behavior**
Tern should detect the license for installed packages in all layers 

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --2.7.0
- Operating System :Ubuntu 
- Installed tern using Docker
- Command -./docker_run.sh ternd "report -i confluentinc/cp-schema-registry:5.5.0" >  output.txt 

**Please attach files if they exist**
- report.
[cp_schemaregistry5.5.0.txt](https://github.com/tern-tools/tern/files/7439170/cp_schemaregistry5.5.0.txt)
-

Hello team,

Please find the above details and kindly get back to me 

Thanks
Raghavendra

**Comment by Raghavendrakamatagi-eng** [comment]
Hello @rnjudge 
Thanks for your response!

We are expecting the license for individual packages found in all layers. Please have a look on attached screenshot(License column is blank) 

![image](https://user-images.githubusercontent.com/58773678/139788526-7487983f-f8f0-40f6-b589-3f6faa6387bd.png)


Note: Tern can able to detect the license for individual packages for other docker images e.g, golang

**Comment by sameer1046** [comment]
https://github.com/tern-tools/tern/pull/1029
It'll be fixed in PR 1029
