### ISSUE TITLE
Dockerfile in the parent directory

### ISSUE THREAD

**Issue by sameer1046** [tern-tools/tern#1078]
Can we have the dockerfile in the parent directory?

I want to build a docker image for recent changes in the source

There is a dockerfile in ci directory which build docker image from a tarball. 

I want donot want to build a tarball instead i copy the directory to the docker image and install it by pip.

I

**Comment by nishakm** [comment]
@sameer1046 I don't quite understand. The current method to create a docker container with the latest tern changes is:
```
$ git clone <this repo>
$ cd <this repo>
$ python setup.py sdist
$ docker build -f ci/Dockerfile -t tern .
```
Are you saying you do not want to run the `python setup.py sdist` step?

**Comment by sameer1046** [comment]
This is fine for me. Thanks
