### ISSUE TITLE
Do not include selinux security context when calculating filesystem hash

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#108]
SELinux adds an extended attribute to all files on a system on which it is enforcing. Plus the attribute is not transferred over to a system where SELinux does not exist, is disabled or not enforced. As a result, if the `tools/fs_hash.sh` script is run on a system with SELinux enforced, the filesystem hash that is produced is specific to that system only and is not portable to another system.

We will have to find some way of excluding SELinux security context from the hash. Either modify the existing shell script to do it or replace it with a python script (if not drastically slow)

**Comment by rnjudge** [comment]
@nishakm was this addressed with https://github.com/tern-tools/tern/commit/57c644c049658f1ac47d2de809238443b96295db?

**Comment by nishakm** [comment]
No...but I think it can be implemented/hacked now, and it would be a good intermediate good-first-issue.
