### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by viki1998** [tern-tools/tern#1089]
in use common - Loading packages from cache: layer "d1dc9db3a9“
I can't understand how this value（d1dc9db3a9） comes from. Is there any help document

**Comment by rnjudge** [comment]
Hi @viki1998 - that value you are inquiring about is the abbreviated hash of full layer filesystem hash:

```
87         logger.debug(                                                           
 88             'Loading packages from cache: layer \"%s\"', layer.fs_hash[:10]) 
```

The `fs_hash` of each layer is the the hashed value of the contents of the layer filesystem (assuming it was created with a tarball). This value gets set by running a shell script (`tools/fs_hash.sh`) which gets the file stats and file content's sha256sum. We then calculate the sha256sum of the contents. If you want to look more at the code that does this, look at `gen_fs_hash()` in `tern/classes/image_layer.py` and `calc_fs_hash()` in `tern/utils/rootfs.py`.

**Comment by rnjudge** [comment]
@viki1998 Let me know if you have any followup questions about this. For now, I am going to close this issue.
