### ISSUE TITLE
skopeo doesn't seem to use Docker image cache when running in container

### ISSUE THREAD

**Issue by meriouma** [tern-tools/tern#1121]
**Describe the bug**
While using Tern in a Docker container, skopeo tries to download the image, although it was already pulled by docker. What I'm trying to achieve here is run Tern on a private image on Github Actions. The steps are (I'm using those steps for other tools and it works fine) :
1. Login to private registry
2. Pull the private image with `docker pull`
3. Run `docker run -v /var/run/docker.sock:/var/run/docker.sock philipssoftware/tern:2.9.1 report -f cyclonedxjson -o output.json -i privaterepo/image:tag` (as per the README)

**Error in terminal**
Although the image was succesfully pulled by docker :
```
2022-02-11 22:17:58,014 - ERROR - skopeo - Error when downloading image: "b'time="2022-02-11T22:17:58Z" level=fatal msg="Error initializing source docker://privaterepo/image:tag: Error reading manifest edge in privaterepo/image:tag: unauthorized: authentication required"\n'"
2022-02-11 22:17:58,015 - CRITICAL - run - Cannot download Container image: "privaterepo/image:tag"
```

**Expected behavior**
Tern running on the already pulled image on the host.

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version' : 2.9.1

**Comment by nishakm** [comment]
Also related to https://github.com/tern-tools/tern/issues/1087 - where skopeo may require either access to `registries.conf` and/or passing the `tls-verify=false` flag.

**Comment by nishakm** [comment]
@meriouma Have you tried mounting your `registries.conf` file from your host to the tern container? Similar to this: https://docs.docker.com/registry/configuration/#overriding-the-entire-configuration-file
