### ISSUE TITLE
Output format cyclonedxjson incorrectly puts license id into license name property

### ISSUE THREAD

**Issue by MarkusGeigerITD** [tern-tools/tern#1137]
When generating an CDX SBOM, tern finds and emits the SPDX license IDs correctly, but puts them into the "name" property instead of the "id" property. 
OWASP Dependency Track is not able to parse the license based on the name property (yet)

Example output 
```
    {
      "name": "ncurses-libs",
      "version": "6.2_p20210612-r0",
      "type": "application",
      "purl": "pkg:apk/alpine/ncurses-libs@6.2_p20210612-r0",
      "licenses": [
        {
          "license": {
            "name": "MIT"
          }
        }
      ]
    }
```

**Expected behavior**
Should be:
```
[...]
"license": {
            "id": "MIT"
          }
[...]
```

**Environment you are running Tern on**
Docker on Ubuntu 20.04

- Output of 'tern --version'
```
Tern version 2.9.1
   python version = 3.9.11 (main, Mar 17 2022, 06:08:17)
```

- Operating System (Linux Distro and version or Mac or Windows)
Docker image was build using the supplied docker-file in ./docker

**Comment by rnjudge** [comment]
cc @coderpatros for another cdx bug :) 

@MarkusGeigerITD what is the expected license name?

**Comment by rnjudge** [comment]
@ivanayov, once we get more clarity on what the "name" field should be, you can work on this :)

**Comment by coderpatros** [comment]
Ah, this might have been something I had meant to check with you @rnjudge. I think I put it in the name property meaning to check if they are _always_ a valid SPDX license ID or if what I was observing was a happy coincidence.

@ivanayov it should be enough to just change this method https://github.com/tern-tools/tern/blob/ba56a93963419f90d2bab2fc9fb819a13cffad0d/tern/formats/cyclonedx/cyclonedx_common.py#L74-L75

Change the `'name'` property name to `'id'`.

**Comment by MarkusGeigerITD** [comment]
(@rnjudge:)
> cc @coderpatros for another cdx bug :)
> 
> @MarkusGeigerITD what is the expected license name?

Hi Rose, thanks for getting back to me so quickly!
When I came across this issue, I was investigating ways to minimize the threat of supply chain attacks via docker base images using only FOSS solutions (and not commercial services like snyk). We are already using OWASP DependencyTrack in our company and when I was made aware of tern, I was excited to see that it supports OWASP's own SBOM format as well. Seems like a perfect match to build a snyk-linke toolchain with only FOSS! I am writing this because I know that it is sometimes difficult to figure out who's to "blame", if two pieces of independent software won't play nicely together.

The CycloneDX json-schema [states](https://github.com/CycloneDX/specification/blob/ccbf7b5781ef534cd62616e3c4221004c7c82a66/schema/bom-1.4.schema.json#L600) only that the license object should have either an id or a name. 
The documentation [here ](https://cyclonedx.org/docs/1.4/json/#metadata_licenses_items_license_id ) seems to be more useful. It suggests that the id property should be used if the license-id is one of the enumeration values listed there and only if not, the license should be treated as a "name" of a license not defined by SPDX (see the remark [here](https://cyclonedx.org/docs/1.4/json/#metadata_licenses_items_license_name))

I have tried to manually replace the property name "name" with "id" before uploading to DependencyTrack and, lo and behold, it works! DT is able to parse the licenses and applied the license policies accordingly - at least for all packages that have exactly one license listed. DT doesn't seem to be able to process multi-licensed packages and I am not sure if that is due to an error in the SBOM format emitted by tern or due a limitation in DT. Maybe @stevespringett could comment on that?

Thank you all for your work!

**Comment by stevespringett** [comment]
Thanks @MarkusGeigerITD 
* CycloneDX supports a [enumerated list of SPDX license IDs](https://cyclonedx.org/docs/1.4/json/#metadata_licenses_items_license_id) (strict validation)
* [Unresolved license names](https://cyclonedx.org/docs/1.4/json/#metadata_licenses_items_license_name)
* [SPDX license expressions](https://cyclonedx.org/docs/1.4/json/#metadata_licenses_items_expression) (not validated)

When importing BOMs into Dependency-Track, components with SPDX license IDs are tracked back to the SPDX license. License names are currently just displayed as is. Support for [SPDX expressions is on the roadmap](https://github.com/DependencyTrack/dependency-track/issues/170), but given that DT is a security tool, improvements to security use cases take priority.

**Comment by MarkusGeigerITD** [comment]
Thanks for the clarification, @stevespringett!

[slightly off-topic remark]
> ... but given that DT is a security tool, improvements to security use cases take priority.

I fully understand and agree - my main focus is on security as well. But in my experience, when it comes to convincing managers to invest time and money into introducing something like DT, the fear of unintentionally depending on a copyleft-licensed component is much stronger than the fear of having an undiscovered vuln..
That legal stuff is a powerful door-opener.
[/slightly off-topic remark]

**Comment by ivanayov** [comment]
I'd like to address it :)
