### ISSUE TITLE
Invalid SPDXID

### ISSUE THREAD

**Issue by vargenau** [tern-tools/tern#1143]
**Describe the bug**
An SPDXID cannot contain underscores.

Tern generates:
```
SPDXID: SPDXRef-ncurses-terminfo-base-6.2_p20210109-r0
```

**To Reproduce**
```
tern report -f spdxtagvalue -i fsfe/reuse:latest -o reuse.spdx
```

**Error in terminal**
```
none
```

**Expected behavior**
SPDXID should be valid. Replace "_" with e.g. "-".

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
```
Tern version 2.9.1

   python version = 3.9.7 (default, Sep 10 2021, 14:59:43) 
```
- Operating System: Ubuntu 21.10

**Comment by rnjudge** [comment]
Ah, this is because the package version has an underscore in it. I can fix it. Thanks for opening, @vargenau .
