### ISSUE TITLE
Debian-inspector conflict while using scancode and tern

### ISSUE THREAD

**Issue by Jeeppler** [tern-tools/tern#1185]
**Describe the bug**

Installing Scancode-toolkit 31.1.1 and Tern  2.10.1 together results in a package conflict, because both rely on a different version of the `debian-inspector` package.

**To Reproduce**

Try to install  Scancode-toolkit 31.1.1 and Tern  2.10.1 together.

packages.txt
~~~
tern==2.10.1
scancode-toolkit[full]==31.1.1
~~~

**Error in terminal**
```
ERROR: Cannot install -r packages.txt (line 1), -r /packages.txt (line 2) and scancode-toolkit[full]==31.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    scancode-toolkit[full] 31.1.1 depends on debian-inspector>=31.0.0
    scancode-toolkit 31.1.1 depends on debian-inspector>=31.0.0
    tern 2.10.1 depends on debian-inspector==30.0.0
```

**Expected behavior**

Scancode-toolkit and Tern use the same `debian-inspector` version.

**Environment you are running Tern on**

- Python version: 3.9

**Comment by vargenau** [comment]
See also #1195

**Comment by rnjudge** [comment]
Thanks for the issue @Jeeppler! I apologize for the delay.. I have been on maternity leave. I will get the debian-inspector dependency updated for Tern. There will be a new release before the holidays.

**Comment by rnjudge** [comment]
I'm not sure why pip thinks Tern depends on `debian-inspector==30.0.0` when requirements.txt says `debian-inspector>=30.0` but nevertheless it will be fixed in the upcoming release.

**Comment by Jeeppler** [comment]
@rnjudge thanks for fixing it.
