### ISSUE TITLE
Ensure that Tern produces SPDX docs conformant to NTIA minimum elements

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#1205]
Make sure that Tern's SPDX SBOMs have all of the minimum elements for an SBOM:
    - Supplier Name
    - Component Name
    - Version of the Component
    - Other Unique Identifiers
    - Dependency Relationship
    - Author of SBOM Data
    - Timestamp

More field mapping information here: https://spdx.github.io/spdx-spec/v2.3/how-to-use/#k22-mapping-ntia-minimum-elements-to-spdx-fields

Tooling to check conformance: https://github.com/spdx/ntia-conformance-checker (perhaps this should also be included in the testing for PRs?)

**Comment by jspeed-meyers** [comment]
I'm glad to help with the testing component. And if `ntia-conformance-checker` needs to adapt to fit `tern`'s testing needs, please feel free to drop in issues, feature requests, or make PRs!

**Comment by rnjudge** [comment]
When I tested a SPDX  document produced by Tern for the `photon:3.0` container image, I got the following results (same results for tag value format):

```
(ternenv) rose@rose-vm:~/ternenv/ntia-conformance-checker/ntia_conformance_checker$ python3 main.py --file ../../tern/photon.json

Is this SBOM NTIA minimum element conformant? False

Individual elements                            | Status
-------------------------------------------------------
All component names provided?                  | True
All component versions provided?               | False
All component identifiers provided?            | True
All component suppliers provided?              | False
SBOM author name provided?                     | False
SBOM creation timestamp provided?              | True
Dependency relationships provided?             | True

```

**Comment by jspeed-meyers** [comment]
@rnjudge, does that look right to you? You can also get JSON output using `--output json` flag.

**Comment by rnjudge** [comment]
@jspeed-meyers not all of it looks correct. Opening an issue/question in the repo now :)

**Comment by rnjudge** [comment]
To summarize, the missing NTIA minimum info in Tern reports is as follows:

1) The container Package does not have a version associated with it.
```
PackageName: photon
SPDXID: SPDXRef-photon-3.0
PackageVersion: 3.0
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
```

2) Packages do not have `Package Supplier` (7.5) information

3) I believe the SBOM author provided status is incorrect. See https://github.com/spdx/ntia-conformance-checker/issues/52
