### ISSUE TITLE
Add purl information to SPDX reports when available

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#1206]
A [purl](https://github.com/package-url/purl-spec) is a URL string used to identify and locate a software package in a mostly universal and uniform way across programing languages, package managers, packaging conventions, tools, APIs and databases.

Tern's SPDX documents are more consumable and interoperable with other tooling if purls are available for the packages.

SPDX supports the inclusion of purls as a `PACKAGE-MANAGER` category of ExternalReference for a package. See https://spdx.github.io/spdx-spec/v2.3/package-information/#721-external-reference-field and https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/#f35-purl.

**Comment by ivanayov** [comment]
I'd like to work on this.
