### ISSUE TITLE
Use itertools to chain packages for efficient looping

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#134]
**Problem Statement**
In order to find the packages in an image layer that are not in previous layers, you need to maintain a 'master list' of packages and for each of the layers, compare with this master list and update it as you go along. This makes inefficient use of memory and forces you to maintain a global variable.

**Describe the Proposal**
Instead of maintaining a 'master list' you could use the itertools's chain method to loop through each of the previous layer's list of packages in order, thus maintaining a 'master list' without allocating memory or having a global variable. Since you are already mounting layers from 0 to x, you can loop through packages in layers from 0 to x-1 to find packages that are unique to x.

**Steps to Implement Proposal**
```
import itertools

for pkg in itertools.chain(x for x in image.layers[:curr]) <-- may not work, need to experiment
```

**Comment by abhaykatheria** [comment]
I think this will do the job.
```
def update_current_layer_pacakges(img_obj,layer_index):
    '''Given an Image and layer index it will update the packages found in that
    particular layer by removing the packages which are already found in previous
    layers.
   '''
    layer_obj = img_obj.layers[layer_index]
    package_list = itertools.chain(layer.packages for layer in img_obj.layers[:layer_index])
    unique = []
    for item in layer_obj.packages:
        if item in package_list :
            layer_obj.packages.remove(item)
```

**Comment by abhaykatheria** [comment]
Hi @nishakm i think this function can replace update_master_list.
```
def update_layer_package_list(img_obj,layer_index):
    '''Given an Image and layer index it will update the packages found in that
    particular layer by removing the packages which are already found in previous
    layers.
    '''
    layer_obj = img_obj.layers[layer_index]
    layers_list = itertools.chain(x for x in img_obj.layers[:layer_index])
    package_list = itertools.chain(pkg.packages for pkg in layers_list)
    for item in layer_obj.packages:
        if item in package_list :
            layer_obj.packages.remove(item)
```
We can call this wherever update_master_list was called and get rid of the master_list

**Comment by nishakm** [comment]
@abhaykatheria Sorry for getting back to you on this so late. It turns out `itertools.chain` doesn't actually make a list of unique items. So this implementation will not work. I will close both the issue and the PR.
