### ISSUE TITLE
Remove dev-requirements.txt file

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#408]
**Problem Statement**
This depends on #404 being merged.
Once we can install using `pip install -e.[dev]` we don't need to run `pip install -r dev-requirements.txt && pip install .` since `setup.cfg` has the requirements.

**Steps to Implement Proposal**
1. Use `pip install -e.[dev]` in ci scripts
2. Remove `dev-requirements.txt` file

**Comment by PrajwalM2212** [comment]
I will work on this
