### ISSUE TITLE
Add functionality to extract Debian license data from copyright text

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#499]
**Describe the Feature**
Debian packages do not contain license metadata. Instead, the license information is contained in the copyright text. This results in an empty license list when you run Tern with the default output against a Debian image/BaseOS.

**Use Cases**
This would be helpful for the default output of Tern, primarily when running against Debian base images.

**Implementation Changes**
Add a function that can parse the copyright text for the licenses in a Debian image and report it as the "License" field for a package.

**Comment by nishakm** [comment]
I was introduced to this project and I think it would be a good option to either incorporate or use as a dependency: https://github.com/nexB/debut

**Comment by mukultaneja** [comment]
@nishakm, I would like to work on this issue.

**Comment by nishakm** [comment]
@rnjudge OK to reassign to @mukultaneja?

**Comment by rnjudge** [comment]
Sure!

**Comment by rnjudge** [comment]
This issue was resolved with PR https://github.com/tern-tools/tern/pull/694. Closing.
