### ISSUE TITLE
Record git project name and sha in "pinned" Dockerfile comment

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#509]
**Description**
When parsing the commands in a Dockerfile, if the parser comes across the `ADD` directive, record the git project name and sha in a comment after the command. i.e.

```ADD tar /folder --> ADD tar /folder # git project name and sha if any```

**To Do**
Update Tern's parser to parse `ADD` arguments. Determine if the argument after `ADD` (i.e. what is being copied in) is a folder and if there's a any git information. If not, make a comment indicating that no git information was found.

**Super Issues**
#454

**Comment by ForgetMe17** [comment]
I want to fix this issue. Here is my plan. We can add a function called `add_git_info()` in `dockerfile.py`, which recieve a line with ADD instruction. First it will check if the argument is a folder. For a folder, it will check if it contains a `.git` folder. Then it will extract git project name from `config` file in `.git`. If it is a git respo cloned, `config` file will have a `remote` section containing `url`, we can get the project name here. For sha info, we can know where the HEAD is from file `HEAD` (i.e. ref: refs/heads/master), then we can find the sha in ref/heads/master. Finally we can append the info at the end of line.

For testcases, there are no ADD instructions in the dockfiles at `test`. Maybe we should add a test dockerfile for this function.

**Comment by nishakm** [comment]
@rnjudge does the above plan sound good to you?

**Comment by rnjudge** [comment]
@ForgetMe17 I like it! Thank you for taking this on.

**Comment by rnjudge** [comment]
@ForgetMe17  I'm also thinking about how we would get the actual folder -- since the `dfobj.structure` ADD command line will just be a string containing the folder name. @nishakm Would we assume that the directory is local on the users working directory and find it that way?

**Comment by nishakm** [comment]
> @ForgetMe17 I'm also thinking about how we would get the actual folder -- since the `dfobj.structure` ADD command line will just be a string containing the folder name. @nishakm Would we assume that the directory is local on the users working directory and find it that way?

This one is dicey - the folder where the Dockerfile exists may not be in a local git repository. So we first have to check if it is. You can't do that by just looking for a `.git` folder because the Dockerfile may exist in a sub folder. You can try to run a git command and see if it fails. That way you know if you are in a git repo or not. From here on, rather than look into the refs in the `.git` folder, you're better off running git commands to get the url, remote branch and commit. Not that these are guaranteed pins but it's the best we can do.

**Comment by ForgetMe17** [comment]
Yes, I think it will be better by running the git commands than finding `.git` folder. Thanks for your suggestion and I am going to work on it!

**Comment by rnjudge** [comment]
This issue was resolved in Release 2.0.0. Closing.
