### ISSUE TITLE
Add 'apt' to Command Library

### ISSUE THREAD

**Issue by oc37ejuc** [tern-tools/tern#512]
**Description**
Add 'apt' to snippets.yml to allow detection of Layer changes made using the 'apt' command.

**Implementation**
Duplicate the snippets.yml entry for 'apt-get'

**References**
tern/command_lib/snippets.yml, lines 9-14

**Super Issues**
n.A.

**Comment by oc37ejuc** [comment]
May I work on this issue, please?

**Comment by nishakm** [comment]
@oc37ejuc sure!

**Comment by oc37ejuc** [comment]
I have a question, regarding the Contribution Guidlines-
under 'After making changes' it states I should run prospector, and fix any issues it flags.
I have just cloned the forked repository, without making any changes yet, and prospector is flagging various issues.
Do I have to deal with all of those as well?

**Comment by nishakm** [comment]
> I have just cloned the forked repository, without making any changes yet, and prospector is flagging various issues.
> Do I have to deal with all of those as well?

Can you paste the steps you took to install the requirements and the output of prospector here? You don't have to fix those, and the CI tests will probably not pick it up.

**Comment by oc37ejuc** [comment]
Steps as follows:

`pip install wheel`
`pip install -e.[dev]`
`prospector .`

The output from prospector is attatched.
[prospector_output.txt](https://github.com/vmware/tern/files/4026529/prospector_output.txt)

**Comment by nishakm** [comment]
Thanks! I'll check it out. Prospector doesn't test yaml files so adding a change to `snippets.yml` will not affect linting. However, it would be great if you could test your change against a docker image that was created using `apt install`. I haven't come across one yet.

**Comment by nishakm** [comment]
@oc37ejuc Can you also file an issue about the prospector errors? I'd appreciate it. Thanks!

**Comment by oc37ejuc** [comment]
@nishakm done :)

**Comment by HeroicHitesh** [comment]
@nishakm Is this issue available for me to work upon?

**Comment by nishakm** [comment]
Sure! Go for it.

**Comment by HeroicHitesh** [comment]
@nishakm Sorry for the delay, today I tried to setup the project on my local using [this](https://github.com/tern-tools/tern/blob/master/CONTRIBUTING.md#setting-up-a-development-environment-on-mac-and-windows) and it gave some error while running `vagrant`. The error was `'pwd': Operation not permitted - getcwd (Errno::EPERM)`
I googled it and found this [Stackoverflow issue](https://stackoverflow.com/questions/32891965/error-while-executing-gem-errnoeperm-operation-not-permitted)
I have never used `vagrant` before but I think we are using some kind of script to install dependancies which needs to be modified to install `gems` here - `/usr/local/bin` as suggested in the Stackoverflow issue.
@nishakm Can you help me with what steps should I take now?

**Comment by sakshi006** [comment]
@nishakm  Can i work on this issue?
I  am new here, contributing for the first time.
Please guide me.

**Comment by nishakm** [comment]
> @nishakm Can i work on this issue?
> I am new here, contributing for the first time.
> Please guide me.

Hi! If you are new to contributing to any open source project, I would first ask that you set up your work environment according to https://github.com/tern-tools/tern/blob/master/CONTRIBUTING.md#setting-up-a-development-environment. Also, you can reach out to me on the slack channel. Follow instructions to get access here: https://github.com/tern-tools/tern/blob/master/CONTRIBUTING.md#slack-channel
