### ISSUE TITLE
Fix "too many branches" lint errors

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#517]
**Description**
Prospector 1.2 currently brings up several "too many branches" errors in the code base.
```

tern/analyze/docker/analyze.py
  Line: 122
    pylint: too-many-branches / Too many branches (18/15)

tern/analyze/docker/run.py
  Line: 102
    pylint: too-many-branches / Too many branches (24/15)

tern/formats/default/generator.py
  Line: 22
    pylint: too-many-branches / Too many branches (16/15)

tern/formats/spdx/spdxtagvalue/generator.py
  Line: 142
    pylint: too-many-branches / Too many branches (16/15) (col 4)
```

**To Do**
We can tackle each "too many branches" instance and submit an issue and a corresponding PR. There may be too many changes to submit a PR for all of them.

**Background**
We will ignore the errors in the meantime. So this is a technical debt task.

**Comment by sjha2048** [comment]
Hi @nishakm , can you please assign me this issue?

**Comment by nishakm** [comment]
@sjha2048 Do you want to work on this whole thing or just part of it? I can only add an `assigned` tag to the issue. So just let me know.

**Comment by sjha2048** [comment]
I would like to work on the first file then move towards other ones gradually.

**Comment by nishakm** [comment]
> I would like to work on the first file then move towards other ones gradually.

Cool! Please file an issue indicating the prospector error with the first file. Reference that issue in your commit message. Thanks so much for working on this!

**Comment by ForgetMe17** [comment]
I came up with this issue too, i split the deeper branches into a separate function to fix it. Is this the proper way to deal with this issue?

**Comment by ForgetMe17** [comment]
This is what i got by running `prospector .` in `tern/tern`:
```
formats/spdx/spdxtagvalue/layer_helpers.py
  Line: 91
    pylint: too-many-branches / Too many branches (22/15)

tools/container_debug.py
  Line: 121
    pylint: no-else-continue / Unnecessary "else" after "continue" (col 16)

tools/verify_invoke.py
  Line: 88
    pylint: too-many-function-args / Too many positional arguments for function call (col 4)
```

**Comment by nishakm** [comment]
> I came up with this issue too, i split the deeper branches into a separate function to fix it. Is this the proper way to deal with this issue?

Yup! The function for which the "too-many-branches" error comes up needs to be decomposed into smaller functions and then called.

**Comment by nishakm** [comment]
@ForgetMe17 this is what I get:
```
tern/analyze/docker/helpers.py
  Line: 45
    pylint: too-many-branches / Too many branches (18/15)

tern/extensions/scancode/executor.py
  Line: 48
    pylint: too-many-branches / Too many branches (18/15)

tern/formats/default/generator.py
  Line: 22
    pylint: too-many-branches / Too many branches (24/15)

tern/formats/spdx/spdxtagvalue/layer_helpers.py
  Line: 91
    pylint: too-many-branches / Too many branches (22/15)
```
Some of these I can tackle quickly as it is code I had recently been working on:
```
tern/extensions/scancode/executor.py
tern/formats/spdx/spdxtagvalue/layer_helpers.py
```
I will make an issue for these.

How about you tackle these?
```
tern/analyze/docker/helpers.py
tern/formats/default/generator.py
```
I can make an issue for each one of these and assign them to you.

**Comment by ForgetMe17** [comment]
Yes! i will work on them.

**Comment by nishakm** [comment]
Fixed.
