### ISSUE TITLE
Use shlex to parse Dockerfile RUN instruction commands

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#521]
**Description**
[shlex](https://docs.python.org/3/library/shlex.html) is a simple POSIX command tokenizer. It's much easier to parse long Dockerfile RUN instructions using this library rather than writing our own method of tokenizing.
This task is to rewrite the current tokenizer (`parse_command` function in `general.py`) using this library.

**Background**
On looking at the type of parsing needed for full shell scripts embedded in the run command, we may need to develop a shell script parser to catch all places where software could have been installed.

**Comment by nishakm** [comment]
Turns out we may need to develop a full-fledged shell script parser in order to catch all the places where pinning might occur. It's a pretty big undertaking so I will take the high-priority label and move this to the near future backlog.

**Comment by zoek1** [comment]
@nishakm can i tackle this in while i write a proposal for GSoC 2020?

**Comment by nishakm** [comment]
@zoek1 Are you sure? This issue could in itself be a proposal for GSoC 2020. You would have to write a shell script parser (or find one that already exists as I am not able to find this). If you were to write one, you would have to take into account nested if, for and case statements. Here is an example Dockerfile just to give you an idea of what we are dealing with: https://github.com/docker-library/golang/blob/69b2283d45ae89c84383d41a9b1aab4d84e5cbae/1.14/buster/Dockerfile
Look at the RUN statement.

**Comment by zoek1** [comment]
Gosh, that's better! Ok, what other task do you recommend to start in the meantime.

**Comment by nishakm** [comment]
We have another GSoC issue: https://github.com/vmware/tern/issues/539. You could work on adding some tests.

**Comment by zoek1** [comment]
Perfect, i'll start working on that :smile:

**Comment by ForgetMe17** [comment]
Maybe we can parse the shell script into `variables`, `command`, `if-statement`, `case-statement` and `for-statement`. 
`variables` contains its `value`
`command` contains `name`, `options` and `words`
`if-statement` and `case-statement` contains `condition` and `branch`
`for-statement` contains `condition` and `loop`

For enviroment variables, we can record them in a dict, marking the place where it is refered.
This is just a draft idea.

**Comment by abhaykatheria** [comment]
Hi everyone,
I found this [bash script parser ](https://github.com/vorpaljs/bash-parser)it does the job well and can be used if we rewrite it in python. But as @nishakm stated it's a huge task and could possibly take the entire GSoC period to work on. I also found other parser but it is poorly documented.
- https://github.com/grncdr/js-shell-parse/

**Comment by ForgetMe17** [comment]
Hi, everyone!
I have found a bash parser in python, [bashlex](https://github.com/idank/bashlex). I think it may be helpful for this issue.

**Comment by nishakm** [comment]
Completed with #743
