### ISSUE TITLE
Find full GitHub project link in Dockerfile lock functionality

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#585]
**Describe the Feature**
There is a pending PR for issue #509 that will append the git project name and sha in a comment for Dockerfile lock functionality. This is a good start but, ideally, we would be able to append the full https://<repolink><reponame> URL to the comment. In many cases the repository will be hosted on GitHub under the 'origin' label (i.e. when you list `git remote -v`) but this is not always the case. The user may have re-named the label from origin to something else or the code may not even be hosted on GitHub. There may also be multiple repos listed.

**Use Cases**
This will enhance the information supplied to the user of Tern's Dockerfile Lock functionality.

**Implementation Changes**
Run `git remote -v` at the top level of the git directory that is being `ADD`ed in the Dockerfile. Significant parsing will need to take place to the output to determine the repo URL. Most changes will take place in `tern/analyze/docker/dockerfile.py` in the `find_git_info()` function although you may also want to create a new function to determine the git project URL.

**Comment by ForgetMe17** [comment]
Maybe i can work on this.

**Comment by rnjudge** [comment]
@ForgetMe17 yes, let's get your other PR merged first and then you can build upon it for this issue :) Thanks!

**Comment by ForgetMe17** [comment]
I think I can work on this issue.

**Comment by rnjudge** [comment]
A PR for this issue was merged to master after the 2.0.0 release. Closing this.
