### ISSUE TITLE
Add remove_upgrade_command function to dockerfile.py

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#595]
**Describe the Feature**
Add `remove_upgrade_command` function to dockerfile.py that, given a dockerfile object, will remove any upgrade-type commands (possibly determined by the package manager) from the RUN lines.

**Use Cases**
This will help lock the dockerfile to be more reproducible by eliminating any "upgrade all" type commands and instead forcing users to pin specific packages.

**Implementation Changes**
You might need to add upgrade commands to `base.yml`.
```
208 def remove_upgrade_cmd(dfobj, upgrade_commands):                                                  
209     '''Given a dockerfile object, remove any upgrade-type commands              
210     determined by the package manger provided.'''                               
211     for i, command_dict in enumerate(dfobj.structure):                          
212         if command_dict['instruction'] == 'RUN':                               
213             # remove upgrade strings taking in to account                                                                        
214             command_dict['content'] = Run command without upgrade
215             command_dict['value'] = Run command without upgrade
```

I think this function in will likely be called in analyze.py after the if statement that `expand_package` is a part of.

**Comment by nishakm** [comment]
I wonder if this is a good idea to do as we also pin the base image to a digest. Would an upgrade affect the installation of a specific version of a package?

**Comment by rnjudge** [comment]
> I wonder if this is a good idea to do as we also pin the base image to a digest. Would an upgrade affect the installation of a specific version of a package? A specific example I am thinking of is `tdnf` which needs the `tdnf update` in order to populate the rpm database in order to run `tdnf install` of any package.

This is a good point. I am also thinking that we could pin a package that gets upgraded to a version by including the upgrade command as an option in the install list for `snippets.yml`. I am going to close this issue.
