### ISSUE TITLE
Change logging and reporting of layer checksums to the layer index

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#608]
**Problem Statement**
Tern's logging and report checksum information is useful in identifying layers in the container image. However, the checksums do not actually match the checksums in the image manifest (they are tern's own checksums). These make it difficult to debug which layer brought in what packages and which layer metadata was not found

**Describe the Proposal**
Change the logging and reporting of the layers to reference the layer checksum from the container image manifest.

**Steps to Implement Proposal**
1. Create a method in the image_layer.py class to return the layer tarball's hash. This is the name of of the file in layer.tar_file.
2. Find all the places where layer.fs_hash[:10] is being used and use the new method instead.

**Comment by rnjudge** [comment]
Had some discussion with Nisha about this proposal. Instead of trying to pull the layer hash from the variety of container image client manifests (that all represent the hash in different ways/places) we will refer to the layers by order. We feel that this is more widely understood and intuitive.
