### ISSUE TITLE
Extracting metadata of packages and modules installed by language package managers

### ISSUE THREAD

**Issue by abhaykatheria** [tern-tools/tern#609]
**Problem Statement**
Currently, Tern does not lists the metadata of packages and modules installed by language-level package managers like pip(#149), npm, yarn, gem, and golang.

**Describe the Proposal**
After this Tern should be able to list all the packages and modules installed via the above-mentioned package managers with their proper metadata.

**Steps to Implement Proposal**
Tern already supports adding snippets to the command library. For each language level package management system we would need to add the required scripts in snippets.yml.
as mentioned [here](https://github.com/vmware/tern/blob/master/docs/adding-to-command-library.md)

**Comment by ForgetMe17** [comment]
Hi @abhaykatheria, are you currently working on this proposal?

**Comment by abhaykatheria** [comment]
@ForgetMe17 yes.

**Comment by rnjudge** [comment]
Since we have gem, npm and pip package managers available, I am going to open an issue specifically for collecting golang packages.
