### ISSUE TITLE
Perform analysis on multistage Dockerfiles

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#612]
**Describe the Feature**
Tern can read a Dockerfile, build and image and analyze the image to provide a report and pin a Dockerfile. However, it cannot do these for multistage Dockerfiles accurately because the intermediate stages get thrown away after a build is complete. Why not enable analysis and pinning for multistage Dockerfiles?

**Use Cases**
Multistage Dockerfiles are the de-facto build mechanism for golang projects in particular. A Dockerfile will typically use the golang image to build and an alpine image to deploy the built golang binary.

**Implementation Changes**
A proposed implementation can look like this:
1. Split the Dockerfile by stage, making a single Dockerfile for each stage
2. Build and analyze each stage
3. For reporting, perhaps organize each stage as a different section and indicate that each is a build stage of the next. Pinning a multistage Dockerfile is straightforward.

**Comment by abhaykatheria** [comment]
@nishakm  that sounds awesome i will start looking into it.

**Comment by ForgetMe17** [comment]
Maybe i can work on this issue!

**Comment by ForgetMe17** [comment]
Hi nisha, I am considering this way of spliting:

Multistage Dockerfile
```
FROM golang:1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/alexellis/href-counter/app . 
CMD ["./app"]  
```
into

Stage 1
```
FROM golang:1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
```

Stage 2
```
FROM golang:1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/alexellis/href-counter/app . # Copy file from previous stage.
CMD ["./app"]  
```
 
I am not spliting into seperate stages since the second stage may need to copy files from the previous stage. We can build these two dockerfiles and perform analysis on each image. Then organize the report by stage.

**Comment by nishakm** [comment]
@ForgetMe17 That makes sense to me. All the information collected when analyzing an image built from Dockerfile1 are stored in the `Image` object. So you can instantiate `stage1 = DockerImage(repotag1)` for the first image and `stage2 = DockerImage(repotag2)` for the second image. But some of the reports do not take more than one image (most notably the SPDX tag-value) so, focusing on the default report and Dockerfile lock is enough for this part.
