### ISSUE TITLE
Use GitPython for all git operations

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#619]
**Describe the Feature**
Some git operations are done using GitPython while others use `subprocess` to shell out to the git command. How about using GitPython for all git commands?

**Use Cases**
Moving to using git commands means we can get rid of the `# nosec` dismissals for some of the commands that shell out.

**Comment by ForgetMe17** [comment]
I will have a try!

**Comment by ForgetMe17** [comment]
Yes！

**Comment by jaindhairyahere** [comment]
I want to have a try. :)
