### ISSUE TITLE
Setup/Teardown takes too long

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#627]
**Describe the bug**
The Setup and Teardown step seems to be taking a much longer time lately.

**To Reproduce**
Example of the time taken:
```
2020-04-08 08:11:47,723 - DEBUG - run - Setting up...
2020-04-08 08:13:15,338 - DEBUG - container - Checking if image "ternd:test-spdx" is available on disk...
```
It looks like it takes about 2 minutes to complete which is quite long for removing files and setting up directories.

**Comment by mukultaneja** [comment]
@nishakm, the function call `yaml.safe_load` (to load cache) is taking a lot of time here. I tried to load cache using a new `thread` and it worked fine but then `load_full_image` started taking much time :(

**Comment by nishakm** [comment]
> @nishakm, the function call `yaml.safe_load` (to load cache) is taking a lot of time here. I tried to load cache using a new `thread` and it worked fine but then `load_full_image` started taking much time :(

This makes sense because of the serialization of data to and from the file. Implementing #50 should solve this issue.

**Comment by nishakm** [comment]
I've decoupled solving #50 to this problem. It turns out, replacing yaml with json for the cache provides better performance and it is reasonably straightforward to fix.
