### ISSUE TITLE
No Scancode header in generated documents

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#643]
**Describe the bug**
Scancode's licensing requires that any document created with it should contain their header. Currently, the documents created by Tern does not have this header.

**Expected behavior**
There should be a notice indicating that some data was collected using Scancode.

**Comment by mukultaneja** [comment]
@nishakm, "Tern Report generated using scancode <github-repo-link>" would be good as a notice string?

**Comment by nishakm** [comment]
> @nishakm, "Tern Report generated using scancode " would be good as a notice string?

Scancode itself generates a header. It needs to be recorded somewhere but I haven't thought about how to do this.

**Comment by mukultaneja** [comment]
ok, I can try to look into it.

**Comment by mukultaneja** [comment]
@nishakm I was wondering how we should print header in the report because we are calling scancode layer by layer and it generates header every time.

**Comment by nishakm** [comment]
> @nishakm I was wondering how we should print header in the report because we are calling scancode layer by layer and it generates header every time.

So what I would do here is put that message in a notice at that layer.
```
def collect_layer_data(layer_obj):
...
    if not result:
        logger.error(
            "No scancode results for this layer: %s", str(error))
        layer_obj.origins.add_notice_to_origins(
            origin_layer, Notice(str(error), 'error'))
    else:
        # make FileData objects for each result
        data = json.loads(result)
       layer_obj.origins.add_notice_to_origins(origin_layer, Notice(data['header'], 'info')) <--- add this line
        for f in data['files']:
            if f['type'] == 'file' and f['size'] != 0:
                files.append(get_scancode_file(f))
    return files
```

**Comment by mukultaneja** [comment]
yeah, I am doing the same here but in this way it is printing the message on every layer in the report. I am just wondering would it be fine in terms of looking/reading-wise the report!

**Comment by nishakm** [comment]
> yeah, I am doing the same here but in this way it is printing the message on every layer in the report. I am just wondering would it be fine in terms of looking/reading-wise the report!

Yeah it will definitely clutter the default report. You could modify the formatting code in `tern/formats/default` to check for notice messages that are equal for each layer and use that at the top of the document.
