### ISSUE TITLE
Feature: roll debug tools verify_invoke.py and container_debug.py into a subcommand debug

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#660]
**Describe the Feature**
I have been using `tern/tools/verify_invoke.py` and `tern/tools/container_debug.py` to test the scripts that get added to `base.yml` and `snippets.yml` or even just for looking around a container filesystem at a certain layer. However, they have been a pain to maintain as the project keeps growing and moving forward. Hence I propose to roll these tools into Tern as a new subcommand called `debug`.

**Use Cases**
"Debugging" container images could work well as a feature for developers to tinker with container image filesystems, although I see this more as a tool for folks working on Tern itself.

**Implementation Changes**
This would just be using functionality in `verify_invoke.py` and `container_debug.py` under a subcommand called `debug` and removing the scripts from the `tools` folder.

**Comment by mukultaneja** [comment]
@rnjudge, I would like to take this feature.

**Comment by rnjudge** [comment]
> @rnjudge, I would like to take this feature.

@nishakm have you started working on this?

**Comment by nishakm** [comment]
@mukultaneja This one is a little out there - technical debt collected back when the project was new. It'll be better if I work on it. Thanks for volunteering!

**Comment by nishakm** [comment]
@rnjudge This would mean adding a new command line argument and that means our Release number would be 3.0.0. Would you prefer I work on this two releases after?

**Comment by rnjudge** [comment]
> @rnjudge This would mean adding a new command line argument and that means our Release number would be 3.0.0. Would you prefer I work on this two releases after?

As discussed, I agree that this is something that can be pushed back. Maybe we can time the feature with the Beta release.
