### ISSUE TITLE
 Yǒu shé me bànfǎ kěyǐ kàn dào yùnxíng guòchéng ma 14/5000 Is there any way to see the running process?

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#673]
tern scanned the file for nearly 10 minutes, and it didn't end. It seemed to hang. Is there any way to see the running process?

(ternenv) [root@localhost hf]# more tern.log
2020-04-29 14:16:08,212 - DEBUG - __main__ - Starting...
2020-04-29 14:16:08,216 - DEBUG - run - Setting up...
2020-04-29 14:16:08,219 - DEBUG - rootfs - Running command: tar -tf base-latest-20191210.tar
2020-04-29 14:16:08,225 - DEBUG - rootfs - Running command: tar -xf base-latest-20191210.tar -C /root/.tern/te
mp
2020-04-29 14:16:09,926 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/558c11b2b15adc493f1dc7d91
1f5eec1bf4bc9e2fa4119dc4267b8579763450f/layer.tar
2020-04-29 14:16:10,494 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/558c11b2b15adc493f1dc7d91
1f5eec1bf4bc9e2fa4119dc4267b8579763450f/layer.tar -C /root/.tern/temp/558c11b2b15adc493f1dc7d911f5eec1bf4bc9e2
fa4119dc4267b8579763450f/contents
2020-04-29 14:16:29,299 - DEBUG - rootfs - Running command: /run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed9
85/hf/tern-master/ternenv/lib64/python3.6/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/558c11b2b15adc4
93f1dc7d911f5eec1bf4bc9e2fa4119dc4267b8579763450f/contents
2020-04-29 14:19:38,917 - DEBUG - common - Reading files in filesystem...

(ternenv) [root@localhost hf]# uname -a
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

(ternenv) [root@localhost temp]# ls
48e3ab07239e906d00f736779268d8832d696d5009f2b1015949fd5dca0ff23d.json  manifest.json  repositories
558c11b2b15adc493f1dc7d911f5eec1bf4bc9e2fa4119dc4267b8579763450f       mergedir       workdir

**Comment by nishakm** [comment]
Can you paste here the results of `ls -al` in the `temp` directory?

**Comment by 00032118** [comment]
(ternenv) [root@localhost temp]# ls -al
total 12
drwxr-xr-x. 5 root root 227 Apr 30 08:22 .
drwxr-xr-x. 3 root root  35 Apr 30 08:19 ..
-rw-r--r--. 1 root root 891 Dec 10 15:36 48e3ab07239e906d00f736779268d8832d696d5009f2b1015949fd5dca0ff23d.json
drwxr-xr-x. 3 root root 142 Apr 30 08:22 558c11b2b15adc493f1dc7d911f5eec1bf4bc9e2fa4119dc4267b8579763450f
-rw-r--r--. 1 root root 212 Jan  1  1970 manifest.json
drwxr-xr-x. 2 root root   6 Apr 30 08:22 mergedir
-rw-r--r--. 1 root root  99 Jan  1  1970 repositories
drwxr-xr-x. 2 root root   6 Apr 30 08:22 workdir
(ternenv) [root@localhost temp]#

**Comment by 00032118** [comment]
Hello, it took about 27 minutes to run, and the analysis result came out. Is this execution time normal? Are there any command parameters or methods that can help me see a more detailed process during execution

**Comment by nishakm** [comment]
> Hello, it took about 27 minutes to run, and the analysis result came out. Is this execution time normal? Are there any command parameters or methods that can help me see a more detailed process during execution

If you're running tern for the first time on a large image, yes, it can take that long. However, I am not really sure why it is taking 10 minutes at line: `2020-04-29 14:19:38,917 - DEBUG - common - Reading files in filesystem...`

Can you attach `tern.log` here?

**Comment by 00032118** [comment]
How can I see more logs of the tern scanning process, are there any parameters or methods to learn more?

**Comment by nishakm** [comment]
What you're seeing is the most amount of logging we have. Anything specific you are looking for?
