### ISSUE TITLE
Tern fails to perform analysis for Buildpack images

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#684]
**Describe the bug**
If you create or pull an image from dockerhub that was created with kpack, Tern fails to perform any analysis. Note: this has been seen on a variety of buildpack images.

**To Reproduce**
```
1. $ docker pull carlocolombo/pet-clinic-007
2. $ tern report -o pet-clinic-007.tern.12.05.2020 -i carlocolombo/pet-clinic-007:latest
```

**Error in terminal**
```
2020-05-13 13:38:09,929 - ERROR - rootfs - Malformed tar: tar: Removing leading `/' from member names
2020-05-13 13:38:09,930 - WARNING - report - Error in loading image: Malformed tarball: /home/toor/.tern/temp/d534ff8ec2cb1b96a73da5fa02d959d80f35250115eebd86cd0a01bfb02ed1f3/layer.tar
2020-05-13 13:38:09,930 - WARNING - run - Cannot retrieve full image metadata
```

**Expected behavior**
Tern would ideally be able to unpack the buildpack image and perform analysis on it.

**Environment you are running Tern on**
Enter all that apply
- Tern @ tip of master
- Ubuntu VM

Possibly related super issue: https://github.com/tern-tools/tern/issues/678

**Comment by nishakm** [comment]
Not related to super issue: #678 

It looks like CNB does not use GNU tar to tar their buildpack tarballs, thus creating leading `/` in tarball members. This is a security concern when extracting (see https://github.com/tern-tools/tern/issues/226). However, it looks like GNU tar will remove the leading `/` by default (see https://www.gnu.org/software/tar/manual/html_node/absolute.html).

Tern reports any messages to stderr as a "Malformed tarball" even though tar takes care of the security issue by default. So I think we just need to check for this message and ignore it if present.
