### ISSUE TITLE
How to understand the  alarm info：

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#687]
How to understand the following alarm：
2020-05-14 15:52:25,813 - WARNING - command_lib - No listing for key |3. Consider adding this listing to command_lib/snippets.yml.

2020-05-14 15:52:25,813 - WARNING - command_lib - No listing for key mkdir. Consider adding this listing to command_lib/snippets.yml.

**Comment by nishakm** [comment]
It's a message about Tern's command library. It basically means "Tern doesn't understand the command 'mkdir' so it doesn't know how the filesystem was created". It's at a WARNING level because it affects the accuracy of the results, hence you should be careful when using the results. We should update the message though. It caters more to those contributing to Tern than users of Tern.

**Comment by 00032118** [comment]
Okay, understand, thank you for your reply.

**Comment by rnjudge** [comment]
@nishakm What about:

```
                warning: Tern has no way to collect 'srcs' package metadata. Manual inspection for this information may be required.
Tern has no way to collect 'copyrights' package metadata. Manual inspection for this information may be required.
```

**Comment by rnjudge** [comment]
For the snippets warning message I propose:
```
Tern has no way to list package metadata using '{listing_key}' command. Manual inspection may be required.
```

^^ This is where the commands like `mkdir` would get represented as the listing_key.

**Comment by nishakm** [comment]
How about:
```
No metadata listing for '{listing_key}' command. Accuracy may be reduced.
```

**Comment by rnjudge** [comment]
Saying "accuracy may be reduced" seems like it implies that some information will be reported that just might not be accurate, when in reality no information is reported for the `listing_key` that triggers the warning message. Thoughts?

**Comment by nishakm** [comment]
> @nishakm Saying "accuracy may be reduced" to me implies that some information will be reported that just might not be accurate, when in reality no information is reported for the `listing_key` that triggers the warning message. Thoughts?

We do have messages like `Licenses found` and `Packages found`. Folks will usually just look at that and say "Tern didn't find anything but I'm pretty sure there's something there". The reality is that we don't know how to get it. Not sure how to communicate this...

**Comment by rnjudge** [comment]
> > @nishakm Saying "accuracy may be reduced" to me implies that some information will be reported that just might not be accurate, when in reality no information is reported for the `listing_key` that triggers the warning message. Thoughts?
> 
> We do have messages like `Licenses found` and `Packages found`. Folks will usually just look at that and say "Tern didn't find anything but I'm pretty sure there's something there". The reality is that we don't know how to get it. Not sure how to communicate this...

Curious what's wrong with `Manual inspection may be required.` or something to that effect... `Manual inspection may reveal additional information` ?

**Comment by nishakm** [comment]
Last suggestion:
`No listing method for '{listing_key}'. Additional analysis may be required`
