### ISSUE TITLE
Increase the file ID corresponding to the license

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#692]
**Describe the Feature**
tern uses the scancode extension function, and the resulting output cannot see which layer or file the license originated from, so it will not be used for subsequent use. Can you consider adding direct output according to the output format supported by the scancode tool itself?
**Use Cases**
Facilitate compliance management of components or modules

**Comment by nishakm** [comment]
You can certainly find that information using the YAML or JSON format. Run `tern report -x scancode -f yaml -o output.yaml` or `tern report -x scancode -f json -o output.json`.

**Comment by rnjudge** [comment]
Hi @00032118 -- just for some context -- the default report is intended to give users a high level overview of their container contents -- almost like a short summary. Adding a list of every single file that scancode finds in each layer would significantly increase the length of this document and defeat the purpose of the summary. As Nisha suggested, please take a look at some of the other output formats. I think you can also use the spdxtagvalue format to find this information.

Closing this bug.
