### ISSUE TITLE
Collect go package metadata for reports

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#695]
**Describe the Feature**
Currently, Tern does not lists the metadata of packages and modules installed using the golang package manager.

**Use Cases**
When images install go packages, it would be useful for Tern to report on the metadata of those packages.

**Implementation Changes**
Tern already supports adding snippets to the command library. It is possible that we might be able to add something to `snippets.yml` for package collection similar to how we collect other package information, but it will likely be more involved. This is something @abhaykatheria is working on for his GSoC project this summer.

**Comment by nishakm** [comment]
Going to close this issue for now as Go modules seem to be the standardized way the community is heading.
