### ISSUE TITLE
Deprecate run_on_image in passthrough.py

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#704]
**Problem Statement**
No extension is currently using run_on_image

**Describe the Proposal**
`run_on_image` was originally created as a convenience function that an extension can use to integrate their scanning tool. However, both examples of extensions, cve_bin_tool and scancode, do not use this function. It is possible that other extensions will not need it either. Hence it should go.

The counter-argument to this is that we still have not come across an externally developed plugin, so we can't say for sure. I propose we wait until an externally developed extension is proposed and has no use for the run_on_image function.

**Comment by rnjudge** [comment]
@jayeritz is going to take this one.
