### ISSUE TITLE
Enable SPDX document validation for CI

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#713]
**Description**
As development increases on the project, it is getting hard to maintain the generation of valid SPDX documents for the container images. So enable CI checks for SPDX if anything in the generator or formatting code changes.

**To Do**
1. Setup requires install of openjdk and the SPDX tools from their release page: https://github.com/spdx/tools/releases
2. Then run `tern report -f spdxtagvalue -i <a chosen image> -o spdx.txt` and run the validation tool on the output.

**Comment by rnjudge** [comment]
The new SPDX validation tool is available here: https://github.com/spdx/tools-java
