### ISSUE TITLE
The license should preferably correspond to the source package, so that the user can clearly obtain the source of the license 

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#729]
Eg :def get_package_licenses(package):
    '''Given a package collect complete list of package licenses'''
    pkg_licenses = set()
    if package.pkg_license:
        pkg = package.name + ":" + package.pkg_license
        #pkg_licenses.add(package.pkg_license)
        pkg_licenses.add(pkg)

    if package.pkg_licenses:
        for pkg_license in package.pkg_licenses:
            if pkg_license:
                pkg = package.name + ":" + pkg_license
                #pkg_licenses.add(pkg_license)
                pkg_licenses.add(pkg)
    return list(pkg_licenses)

**Comment by rnjudge** [comment]
I will also add, if you want a default report to be formatted as you are suggesting, it's possible and fairly straightforward to create your own report formatting plugin. We know that there might be unique requirements for different users and this is why the reporting formats are designed as plugins. There is guidance on how to create your own plugin [here](https://github.com/tern-tools/tern/blob/master/docs/creating-custom-templates.md) (If you want to use the default report mapping you can ignore the first step of those directions).  It's also possible to incorporate the change you suggested into your development branch and install your version of Tern with the changes locally.

**Comment by nishakm** [comment]
@00032118 I agree with @rnjudge on this. If you would like to maintain your own report formatting plugin for Tern, you can do so in a separate git repository. Then you can submit a PR asking for that plugin to be included in the list of [recognized plugins](https://github.com/tern-tools/tern/blob/master/setup.cfg#L44)

**Comment by 00032118** [comment]
There are too many other formats, it is not easy to get clear information
