### ISSUE TITLE
Modify the code when using scancode extension to display the file or binary name corresponding to the license.

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#730]
Eg:
 if file_dict['licenses']:
       #fd.licenses = [l['short_name'] for l in file_dict['licenses']]
       fd.licenses = (('%s:' + ','.join([l['short_name'] for l in file_dict['licenses']])) %(fspath)).split()
    if file_dict['license_expressions']:
        fd.license_expressions = (('%s:' + ','.join(file_dict['license_expressions'])) %(fspath)).split()

**Comment by rnjudge** [comment]
You can get this information from the spdxtagvalue, json or yaml reports using scancode.

**Comment by 00032118** [comment]
When using the extended scancode tool, you can only use the json format, but the output content in this format is too much, the defaule format output is simple and more intuitive, if you add the name, it is easier to read

**Comment by nishakm** [comment]
@00032118 actually, there is a PR open for a HTML format which will convert the json into a more approachable UI so you can see what license came from what file. Would this format help?

**Comment by 00032118** [comment]
a PR open for a HTML format??

**Comment by nishakm** [comment]
See https://github.com/tern-tools/tern/pull/720

**Comment by 00032118** [comment]
thank you，The HTML format is very good and easier to read. I still think that it is better to see the name of the file or package when the license is synchronized. Otherwise, I don’t know the source and it won’t help.
