### ISSUE TITLE
 How to scan images without basic package management tools

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#738]
In the image of the ubuntu system, if you want to reduce the size of the image file, the command like dpkg may not be available, or simplified, and the --get-selections parameter cannot be found, which will cause the scan to fail. How to solve this problem is better ?

**Comment by rnjudge** [comment]
This is often the case with minimal images -- no package management tools limits what Tern can find. If there are no package management tools present I would suggest using scancode to at least find file level licenses.

**Comment by 00032118** [comment]
ok，thank you
