### ISSUE TITLE
Deprecate instantiating a derived Image class with multiple options

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#747]
**Description**
At the time of creating the Image class, it was not known how users usually reference images. Now we know that they mostly reference them either in the `repo:tag` format or the `repo@digest_type:digest` format. There is already functionality to parse the two. Hence we do not need to record Image ID. We can just check to see if what is instantiated follows these two formats.

**To Do**
1. Modify the Image class to be instantiated with a generic `repotag` property
2. Remove the ImageID property
3. Test functionality

**Background**
This is related to PR #734 

**Super Issues**
#678

**Comment by mukultaneja** [comment]
@nishakm, can I take this issue?

**Comment by nishakm** [comment]
@mukultaneja go for it!
