### ISSUE TITLE
Report RUN command statements that are non-deterministic like if and case statements

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#763]
**Describe the Feature**
Currently, the report notices just says that if, case and for statements are unrecognizable. It would be nice to add notices for non-deterministic branching statements like if and case statements as you could only know the status of the branch at build time.

**Implementation Changes**
The new shell script parser produces a dictionary that will identify if and case statements. We could just look at this object and extract the if and case statements to create notices for them.

**Comment by nishakm** [comment]
@ForgetMe17 Do you want to work on this as a follow up to #521?

**Comment by ForgetMe17** [comment]
Yes!
