### ISSUE TITLE
Tern has no concept of WORKDIR directory (required to collect go module info)

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#766]
**Describe the bug**
Most golang Dockerfiles will have a `WORKDIR` where the go modules get installed. i.e.

```
# Start from the latest golang base image
FROM golang:1.14-alpine as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o swag cmd/swag/main.go
```

If a `WORKDIR` is established, all the proceeding `RUN` , `CMD` , `ADD` , `COPY` , or `ENTRYPOINT` commands will be executed in this `WORKDIR`. Tern currently has no concept of a `WORKDIR`. This is an issue when it comes to analyzing the go modules in a docker image because the go command is only present in the `WORKDIR`, compared to most package manager utilities that are universally available in the image. The command `go list -m all | tail -n +2 | cut -d ' ' -f1` which attempts to collect the module names, will return `Command failed. go list -m: not using modules` if not executed from the proper WORKDIR directory. However, if you change the `base.yml` command to cd into the `WORKDIR` first, then the command executes without errors. cd-ing into the `WORKDIR` directory is not something we can do from `base.yml` because we won't know the name of the `WORKDIR` directory and there is currently no way to reference this.

**To Reproduce**
1. Add `go` package manager to base.yml and snippets.yml.
2. Run tern on a go image (similar to Dockerfile above)
3. If you change `base.yml` to cd into the `WORKDIR` first by running `cd /app; /usr/local/go/bin/go list -m all | tail -n +2 | cut -d ' ' -f1` to collect go modules, the command will work and Tern will output the go modules in the report. If you only use `/usr/local/go/bin/go list -m all | tail -n +2 | cut -d ' ' -f1` the command will fail.
4. See error/output below.

**Error in terminal**
Output when you cd into the WORKDIR first in `base.yml`:
```
 File licenses found in Layer:  None
        Packages found in Layer:  github.com/BurntSushi/toml-v0.3.1, github.com/KyleBanks/depth-v1.2.1,
 github.com/PuerkitoBio/purell-v1.1.1, github.com/PuerkitoBio/urlesc-v0.0.0-20170810143723-de5bf2ad4578,
 github.com/alecthomas/template-v0.0.0-20190718012654-fb15b899a751, github.com/cpuguy83/go-md2man/v2-
v2.0.0-20190314233015-f79a8a8ca69d, github.com/davecgh/go-spew-v1.1.1, github.com/ghodss/yaml-v1.0.0, 
github.com/gin-contrib/gzip-v0.0.1, github.com/gin-contrib/sse-v0.1.0, github.com/gin-gonic/gin-v1.4.0, github.com/go-
openapi/jsonpointer-v0.19.3, github.com/go-openapi/jsonreference-v0.19.3, github.com/go-openapi/spec-v0.19.4, 
github.com/go-openapi/swag-v0.19.5, github.com/golang/protobuf-v1.3.1, github.com/json-iterator/go-v1.1.6, github.com/kr
/pretty-v0.1.0, github.com/kr/pty-v1.1.5, github.com/kr/text-v0.1.0, github.com/mailru/easyjson-v0.0.0-20190626092158-
b2ccc519800e, github.com/mattn/go-isatty-v0.0.8, github.com/modern-go/concurrent-v0.0.0-20180306012644-
bacd9c7ef1dd, github.com/modern-go/reflect2-v1.0.1, github.com/pkg/errors-v0.8.1, github.com/pmezard/go-difflib-v1.0.0, 
github.com/russross/blackfriday/v2-v2.0.1, github.com/satori/go.uuid-v1.2.0, github.com/shopspring/decimal-v1.2.0, 
github.com/shurcooL/sanitized_anchor_name-v1.0.0, github.com/stretchr/objx-v0.2.0, github.com/stretchr/testify-v1.4.0,
 github.com/swaggo/files-v0.0.0-20190704085106-630677cd5c14, github.com/swaggo/gin-swagger-v1.2.0, 
github.com/ugorji/go-v1.1.5-pre, github.com/ugorji/go/codec-v1.1.5-pre, github.com/urfave/cli-v1.20.0, github.com/urfave
/cli/v2-v2.1.1, golang.org/x/crypto-v0.0.0-20190611184440-5c40567a22f8, golang.org/x/net-v0.0.0-20190827160401-
ba9fcec4b297, golang.org/x/sync-v0.0.0-20190423024810-112230192c58, golang.org/x/sys-
v0.0.0-20190616124812-15dcb6c0061f, golang.org/x/text-v0.3.2, golang.org/x/tools-
v0.0.0-20190614205625-5aca471b1d59, gopkg.in/check.v1-v1.0.0-20180628173108-788fd7840127, gopkg.in/go-
playground/assert.v1-v1.2.1, gopkg.in/go-playground/validator.v8-v8.18.2, gopkg.in/yaml.v2-v2.2.2

        Licenses found in Layer:  None
```

Output when you don't `cd` into the `WORKDIR`:
```
020-07-13 14:02:56,250 - DEBUG - rootfs - Running command: sudo unshare -pf --mount-proc=/home/rjudge/.tern/temp/mergedir/proc chroot /home/rjudge/.tern/temp/mergedir /bin/sh -c /usr/local/go/bin/go list -m all | tail -n +2 | cut -d ' ' -f1
2020-07-13 14:02:56,279 - ERROR - rootfs - Command failed. go list -m: not using modules
```

**Expected behavior**
Tern should be executing from the `WORKDIR` directory, if it exists.

**Comment by abhaykatheria** [comment]
For each layer, we can check its created_by field to check whether it is created from the command which sets the `WORKDIR`. An example of such a command could be.
```'created_by': '/bin/sh -c #(nop) WORKDIR /go'```

We can add a check in tern/analyze/analyze.py ```analyze_subsequent_layers()```
which can have  definition something like this :
```
def get_layer_workdir(layer_obj):
    match = re.search(r"\bWORKDIR\ (\/\w+)+\b", layer_obj.created_by)
    if match:
        return match.group()
    else:
        return None
```
once we get workdir we can cd into into it using.

``` container.docker_command(container.execute, container, shell, '-c', 'cd' + workdir)```

I don't know for sure whether this approach will work but we can start from here.

**Comment by rnjudge** [comment]
Finding the layer `WORKDIR` from the `created_by` command looks good. I think we can put the `get_layer_workdir()` function in `image_layer.py`. 

As you said, `analyze_subsequent_layers()` is where you can make the call to `get_layer_workdir()`. If the workdir exists, can we just `os.chdir()` to that directory before running `add_base_packages` which invokes commands from base.yml against the layer? 

You'll also need to figure out a way to keep track of the workdir, since not all layers will have a workdir, but any layer that comes after the WORKDIR command should be executed in that workdir directory. The logic will also need to account for if there are two workdirs. In the example dockerfile below, cmd1,2 and 3 should be executed from /dir1 WORKDIR but cmd4 and 5 will need to be executed from /dir2.

```
WORKDIR /dir1
RUN cmd1
RUN cmd2
RUN cmd3

WORKDIR/dir2
RUN cmd4
RUN cmd5
```

@nishakm thoughts?

**Comment by mukultaneja** [comment]
@rnjudge I think we can get this information inside `config` section of config.json

```
{
	"architecture": "amd64",
	"config": {
		"Hostname": "",
		"Domainname": "",
		"User": "",
		"AttachStdin": false,
		"AttachStdout": false,
		"AttachStderr": false,
		"Tty": false,
		"OpenStdin": false,
		"StdinOnce": false,
		"Env": ["PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "GOLANG_VERSION=1.14.3", "GOPATH=/go"],
		"Cmd": ["bash"],
		"ArgsEscaped": true,
		"Image": "sha256:2b7d6672112d14282cdc6f68af684b6cb0fdc963eb92785653e66d59e9a1c29f",
		"Volumes": null,
		"WorkingDir": "/go",
		"Entrypoint": null,
		"OnBuild": null,
		"Labels": null
	},
	"container": "6ed4f1d2b07e97fd0cf058ac0aef4357a9e8ad2e9047243966c53a66779a90d0",
	"container_config": {
		"Hostname": "6ed4f1d2b07e",
		"Domainname": "",
		"User": "",
		"AttachStdin": false,
		"AttachStdout": false,
		"AttachStderr": false,
		"Tty": false,
		"OpenStdin": false,
		"StdinOnce": false,
		"Env": ["PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "GOLANG_VERSION=1.14.3", "GOPATH=/go"],
		"Cmd": ["/bin/sh", "-c", "#(nop) WORKDIR /go"],
		"ArgsEscaped": true,
		"Image": "sha256:2b7d6672112d14282cdc6f68af684b6cb0fdc963eb92785653e66d59e9a1c29f",
		"Volumes": null,
		"WorkingDir": "/go",
		"Entrypoint": null,
		"OnBuild": null,
		"Labels": {}
	},
	"created": "2020-05-16T08:15:09.426213695Z",
	"docker_version": "18.09.7",
	"history": [{
		"created": "2020-05-15T06:28:12.60008518Z",
		"created_by": "/bin/sh -c #(nop) ADD file:fb54c709daa205bf9d04eb3d90ba068db4c34dfe3b6ec0d7691f677286120903 in / "
	}, {
		"created": "2020-05-15T06:28:13.142776633Z",
		"created_by": "/bin/sh -c #(nop)  CMD [\"bash\"]",
		"empty_layer": true
	}, {
		"created": "2020-05-15T17:32:13.507479591Z",
		"created_by": "/bin/sh -c apt-get update \u0026\u0026 apt-get install -y --no-install-recommends \t\tca-certificates \t\tcurl \t\tnetbase \t\twget \t\u0026\u0026 rm -rf /var/lib/apt/lists/*"
	}, {
		"created": "2020-05-15T17:32:19.176657033Z",
		"created_by": "/bin/sh -c set -ex; \tif ! command -v gpg \u003e /dev/null; then \t\tapt-get update; \t\tapt-get install -y --no-install-recommends \t\t\tgnupg \t\t\tdirmngr \t\t; \t\trm -rf /var/lib/apt/lists/*; \tfi"
	}, {
		"created": "2020-05-15T17:32:41.11765058Z",
		"created_by": "/bin/sh -c apt-get update \u0026\u0026 apt-get install -y --no-install-recommends \t\tgit \t\tmercurial \t\topenssh-client \t\tsubversion \t\t\t\tprocps \t\u0026\u0026 rm -rf /var/lib/apt/lists/*"
	}, {
		"created": "2020-05-16T08:14:55.906410569Z",
		"created_by": "/bin/sh -c apt-get update \u0026\u0026 apt-get install -y --no-install-recommends \t\tg++ \t\tgcc \t\tlibc6-dev \t\tmake \t\tpkg-config \t\u0026\u0026 rm -rf /var/lib/apt/lists/*"
	}, {
		"created": "2020-05-16T08:14:56.195025229Z",
		"created_by": "/bin/sh -c #(nop)  ENV GOLANG_VERSION=1.14.3",
		"empty_layer": true
	}, {
		"created": "2020-05-16T08:15:07.773403646Z",
		"created_by": "/bin/sh -c set -eux; \t\tdpkgArch=\"$(dpkg --print-architecture)\"; \tcase \"${dpkgArch##*-}\" in \t\tamd64) goRelArch='linux-amd64'; goRelSha256='1c39eac4ae95781b066c144c58e45d6859652247f7515f0d2cba7be7d57d2226' ;; \t\tarmhf) goRelArch='linux-armv6l'; goRelSha256='b1c3a648c3c8877b98dfba1996dec604c8fb8899db07994b2dfd47b0063367c8' ;; \t\tarm64) goRelArch='linux-arm64'; goRelSha256='a7a593e2ee079d83a1943edcd1c9ed2dae7529666fce04de8c142fb61c7cdd3e' ;; \t\ti386) goRelArch='linux-386'; goRelSha256='46f8c744788103e8aeceb12c7d71eb16a58fe43e7e4711055fa9ef4bae50bff7' ;; \t\tppc64el) goRelArch='linux-ppc64le'; goRelSha256='329359e2b72839696e78b6c0a96fd939e28e7435d852f31107f68037dd5f7442' ;; \t\ts390x) goRelArch='linux-s390x'; goRelSha256='1aad312fc7fa85d663e8226237cc7519b2599b88a213098abc10de8e84d6cfab' ;; \t\t*) goRelArch='src'; goRelSha256='93023778d4d1797b7bc6a53e86c3a9b150c923953225f8a48a2d5fabc971af56'; \t\t\techo \u003e\u00262; echo \u003e\u00262 \"warning: current architecture ($dpkgArch) does not have a corresponding Go binary release; will be building from source\"; echo \u003e\u00262 ;; \tesac; \t\turl=\"https://golang.org/dl/go${GOLANG_VERSION}.${goRelArch}.tar.gz\"; \twget -O go.tgz \"$url\"; \techo \"${goRelSha256} *go.tgz\" | sha256sum -c -; \ttar -C /usr/local -xzf go.tgz; \trm go.tgz; \t\tif [ \"$goRelArch\" = 'src' ]; then \t\techo \u003e\u00262; \t\techo \u003e\u00262 'error: UNIMPLEMENTED'; \t\techo \u003e\u00262 'TODO install golang-any from jessie-backports for GOROOT_BOOTSTRAP (and uninstall after build)'; \t\techo \u003e\u00262; \t\texit 1; \tfi; \t\texport PATH=\"/usr/local/go/bin:$PATH\"; \tgo version"
	}, {
		"created": "2020-05-16T08:15:08.234801923Z",
		"created_by": "/bin/sh -c #(nop)  ENV GOPATH=/go",
		"empty_layer": true
	}, {
		"created": "2020-05-16T08:15:08.422676483Z",
		"created_by": "/bin/sh -c #(nop)  ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		"empty_layer": true
	}, {
		"created": "2020-05-16T08:15:09.210693095Z",
		"created_by": "/bin/sh -c mkdir -p \"$GOPATH/src\" \"$GOPATH/bin\" \u0026\u0026 chmod -R 777 \"$GOPATH\""
	}, {
		"created": "2020-05-16T08:15:09.426213695Z",
		"created_by": "/bin/sh -c #(nop) WORKDIR /go",
		"empty_layer": true
	}],
	"os": "linux",
	"rootfs": {
		"type": "layers",
		"diff_ids": ["sha256:8c02234b86056c009036ff0c31efb9a726412392d9872dacf95103767ac3b101", "sha256:7cc1c2d7e744369899e8affd52f9be62076b1ef0205f02ed11547bb5327e5a43", "sha256:760e8d95cf58e8696de9ba210ef58522750aee7a1f24c15695f493582002c08e", "sha256:88cfc2fcd059f99b165d045b00500d40892c5afaa7181a95d9936350320c8f9c", "sha256:2f6bb5712e226a770b210eaaa656fdedcd1ad80483cc8c7ad898b461edd4c7e8", "sha256:dff97196d86d5db405c3158fea21a1889392caa916ab206d311f1de5dd926752", "sha256:a3687a50e8622cb3be46ca422497d06f2875011fde18fe61be457b79c1edd552"]
	}
}
```

**Comment by nishakm** [comment]
> Finding the layer `WORKDIR` from the `created_by` command looks good. I think we can put the `get_layer_workdir()` function in `image_layer.py`.
> 
> As you said, `analyze_subsequent_layers()` is where you can make the call to `get_layer_workdir()`. If the workdir exists, can we just `os.chdir()` to that directory before running `add_base_packages` which invokes commands from base.yml against the layer? Another thought would be to append the `cd /workdir` command to the `base.yml` command that gets invoked in `add_base_packages()`.
> 
> You'll also need to figure out a way to keep track of the workdir, since not all layers will have a workdir, but any layer that comes after the WORKDIR command should be executed in that workdir directory. The logic will also need to account for if there are two workdirs. In the example dockerfile below, cmd1,2 and 3 should be executed from /dir1 WORKDIR but cmd4 and 5 will need to be executed from /dir2.
> 
> ```
> WORKDIR /dir1
> RUN cmd1
> RUN cmd2
> RUN cmd3
> 
> WORKDIR/dir2
> RUN cmd4
> RUN cmd5
> ```
> 
> @nishakm thoughts?

Sounds reasonable. One thing to consider is that you could use ENV to set a variable and then do WORKDIR $var. So you may have to keep track of that too. Not sure if the config has all the ENV set for replacement...

**Comment by nishakm** [comment]
> @rnjudge I think we can get this information inside `config` section of config.json
> 
> ```
> {
> 	"architecture": "amd64",
> 	"config": {
> 		"Hostname": "",
> 		"Domainname": "",
> 		"User": "",
> 		"AttachStdin": false,
> 		"AttachStdout": false,
> 		"AttachStderr": false,
> 		"Tty": false,
> 		"OpenStdin": false,
> 		"StdinOnce": false,
> 		"Env": ["PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "GOLANG_VERSION=1.14.3", "GOPATH=/go"],
> 		"Cmd": ["bash"],
> 		"ArgsEscaped": true,
> 		"Image": "sha256:2b7d6672112d14282cdc6f68af684b6cb0fdc963eb92785653e66d59e9a1c29f",
> 		"Volumes": null,
> 		"WorkingDir": "/go",
> 		"Entrypoint": null,
> 		"OnBuild": null,
> 		"Labels": null
> 	},
> 	"container": "6ed4f1d2b07e97fd0cf058ac0aef4357a9e8ad2e9047243966c53a66779a90d0",
> 	"container_config": {
> 		"Hostname": "6ed4f1d2b07e",
> 		"Domainname": "",
> 		"User": "",
> 		"AttachStdin": false,
> 		"AttachStdout": false,
> 		"AttachStderr": false,
> 		"Tty": false,
> 		"OpenStdin": false,
> 		"StdinOnce": false,
> 		"Env": ["PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "GOLANG_VERSION=1.14.3", "GOPATH=/go"],
> 		"Cmd": ["/bin/sh", "-c", "#(nop) WORKDIR /go"],
> 		"ArgsEscaped": true,
> 		"Image": "sha256:2b7d6672112d14282cdc6f68af684b6cb0fdc963eb92785653e66d59e9a1c29f",
> 		"Volumes": null,
> 		"WorkingDir": "/go",
> 		"Entrypoint": null,
> 		"OnBuild": null,
> 		"Labels": {}
> 	},
> 	"created": "2020-05-16T08:15:09.426213695Z",
> 	"docker_version": "18.09.7",
> 	"history": [{
> 		"created": "2020-05-15T06:28:12.60008518Z",
> 		"created_by": "/bin/sh -c #(nop) ADD file:fb54c709daa205bf9d04eb3d90ba068db4c34dfe3b6ec0d7691f677286120903 in / "
> 	}, {
> 		"created": "2020-05-15T06:28:13.142776633Z",
> 		"created_by": "/bin/sh -c #(nop)  CMD [\"bash\"]",
> 		"empty_layer": true
> 	}, {
> 		"created": "2020-05-15T17:32:13.507479591Z",
> 		"created_by": "/bin/sh -c apt-get update \u0026\u0026 apt-get install -y --no-install-recommends \t\tca-certificates \t\tcurl \t\tnetbase \t\twget \t\u0026\u0026 rm -rf /var/lib/apt/lists/*"
> 	}, {
> 		"created": "2020-05-15T17:32:19.176657033Z",
> 		"created_by": "/bin/sh -c set -ex; \tif ! command -v gpg \u003e /dev/null; then \t\tapt-get update; \t\tapt-get install -y --no-install-recommends \t\t\tgnupg \t\t\tdirmngr \t\t; \t\trm -rf /var/lib/apt/lists/*; \tfi"
> 	}, {
> 		"created": "2020-05-15T17:32:41.11765058Z",
> 		"created_by": "/bin/sh -c apt-get update \u0026\u0026 apt-get install -y --no-install-recommends \t\tgit \t\tmercurial \t\topenssh-client \t\tsubversion \t\t\t\tprocps \t\u0026\u0026 rm -rf /var/lib/apt/lists/*"
> 	}, {
> 		"created": "2020-05-16T08:14:55.906410569Z",
> 		"created_by": "/bin/sh -c apt-get update \u0026\u0026 apt-get install -y --no-install-recommends \t\tg++ \t\tgcc \t\tlibc6-dev \t\tmake \t\tpkg-config \t\u0026\u0026 rm -rf /var/lib/apt/lists/*"
> 	}, {
> 		"created": "2020-05-16T08:14:56.195025229Z",
> 		"created_by": "/bin/sh -c #(nop)  ENV GOLANG_VERSION=1.14.3",
> 		"empty_layer": true
> 	}, {
> 		"created": "2020-05-16T08:15:07.773403646Z",
> 		"created_by": "/bin/sh -c set -eux; \t\tdpkgArch=\"$(dpkg --print-architecture)\"; \tcase \"${dpkgArch##*-}\" in \t\tamd64) goRelArch='linux-amd64'; goRelSha256='1c39eac4ae95781b066c144c58e45d6859652247f7515f0d2cba7be7d57d2226' ;; \t\tarmhf) goRelArch='linux-armv6l'; goRelSha256='b1c3a648c3c8877b98dfba1996dec604c8fb8899db07994b2dfd47b0063367c8' ;; \t\tarm64) goRelArch='linux-arm64'; goRelSha256='a7a593e2ee079d83a1943edcd1c9ed2dae7529666fce04de8c142fb61c7cdd3e' ;; \t\ti386) goRelArch='linux-386'; goRelSha256='46f8c744788103e8aeceb12c7d71eb16a58fe43e7e4711055fa9ef4bae50bff7' ;; \t\tppc64el) goRelArch='linux-ppc64le'; goRelSha256='329359e2b72839696e78b6c0a96fd939e28e7435d852f31107f68037dd5f7442' ;; \t\ts390x) goRelArch='linux-s390x'; goRelSha256='1aad312fc7fa85d663e8226237cc7519b2599b88a213098abc10de8e84d6cfab' ;; \t\t*) goRelArch='src'; goRelSha256='93023778d4d1797b7bc6a53e86c3a9b150c923953225f8a48a2d5fabc971af56'; \t\t\techo \u003e\u00262; echo \u003e\u00262 \"warning: current architecture ($dpkgArch) does not have a corresponding Go binary release; will be building from source\"; echo \u003e\u00262 ;; \tesac; \t\turl=\"https://golang.org/dl/go${GOLANG_VERSION}.${goRelArch}.tar.gz\"; \twget -O go.tgz \"$url\"; \techo \"${goRelSha256} *go.tgz\" | sha256sum -c -; \ttar -C /usr/local -xzf go.tgz; \trm go.tgz; \t\tif [ \"$goRelArch\" = 'src' ]; then \t\techo \u003e\u00262; \t\techo \u003e\u00262 'error: UNIMPLEMENTED'; \t\techo \u003e\u00262 'TODO install golang-any from jessie-backports for GOROOT_BOOTSTRAP (and uninstall after build)'; \t\techo \u003e\u00262; \t\texit 1; \tfi; \t\texport PATH=\"/usr/local/go/bin:$PATH\"; \tgo version"
> 	}, {
> 		"created": "2020-05-16T08:15:08.234801923Z",
> 		"created_by": "/bin/sh -c #(nop)  ENV GOPATH=/go",
> 		"empty_layer": true
> 	}, {
> 		"created": "2020-05-16T08:15:08.422676483Z",
> 		"created_by": "/bin/sh -c #(nop)  ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
> 		"empty_layer": true
> 	}, {
> 		"created": "2020-05-16T08:15:09.210693095Z",
> 		"created_by": "/bin/sh -c mkdir -p \"$GOPATH/src\" \"$GOPATH/bin\" \u0026\u0026 chmod -R 777 \"$GOPATH\""
> 	}, {
> 		"created": "2020-05-16T08:15:09.426213695Z",
> 		"created_by": "/bin/sh -c #(nop) WORKDIR /go",
> 		"empty_layer": true
> 	}],
> 	"os": "linux",
> 	"rootfs": {
> 		"type": "layers",
> 		"diff_ids": ["sha256:8c02234b86056c009036ff0c31efb9a726412392d9872dacf95103767ac3b101", "sha256:7cc1c2d7e744369899e8affd52f9be62076b1ef0205f02ed11547bb5327e5a43", "sha256:760e8d95cf58e8696de9ba210ef58522750aee7a1f24c15695f493582002c08e", "sha256:88cfc2fcd059f99b165d045b00500d40892c5afaa7181a95d9936350320c8f9c", "sha256:2f6bb5712e226a770b210eaaa656fdedcd1ad80483cc8c7ad898b461edd4c7e8", "sha256:dff97196d86d5db405c3158fea21a1889392caa916ab206d311f1de5dd926752", "sha256:a3687a50e8622cb3be46ca422497d06f2875011fde18fe61be457b79c1edd552"]
> 	}
> }
> ```

Yup! We already do this for `ADD`. So we need to also include this functionality for `WORKDIR`.

**Comment by rnjudge** [comment]
@abhaykatheria as Mukul pointed out, the `WorkingDir` is accessible in the image's `config` dictionary property. The image is is available in the `image_obj` variable in `analyze_subseqent_layers()`.
