### ISSUE TITLE
"No known shell found in image" when running Tern as a container for Alpine based image.

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#769]
**Describe the bug**
If you use the Tern container to get the SBoM for an Alpine base image, no shell is found and therefore, no information is collected in the report. 

**To Reproduce**
1. Build the ternd image according to the README.
2. Run `./docker_run.sh workdir ternd:latest "report -i golang:1.14-alpine" > output.txt`
3. Look at the output file.

**Error in terminal**
```
Docker image: golang:1.14-alpine:
        Layer: 5cd3e127fc:
                warning: No known shell found in image. Cannot invoke commands

                info: Found 'Alpine Linux v3.11' in /etc/os-release.
        File licenses found in Layer:  None
        Packages found in Layer:  None
        Licenses found in Layer:  None
------------------------------------------------
<snip>
error: Cannot invoke commands without a shell
```

**Expected behavior**
If you examine the golang tarball, a shell is present and should be accessible to assist with package collection.

**Environment you are running Tern on**
This is observed at the tip of master.

**Comment by rnjudge** [comment]
The issue of not finding the shell for Alpine images has to do with the shell location symlinks in the Alpine image when running Tern in a container. This is the line in the `get_shell()` function in tern/analyze/common.py that returns false so the shell is not found: `if os.path.exists(os.path.join(cwd, sh[1:])):`. Even though the directory (os.path.join(cwd, sh[1:])) exists, `os.path.exists` returns false here. I added some debug functionality to `get_shell()` to list out the contents of the bin directory and found for the base layer that /bin/sh is symlinked to busybox:
```
$ ls -la bin
lrwxrwxrwx  1 root root     12 Apr 23 06:25 sh -> /bin/busybox
```
While, `os.path.islink()` recognizes bin/sh  as a symlink, the symlink is broken somehow. I deduced this because`os.path.exists(path)` will "Return True if path refers to an existing path. Returns False for broken symbolic links." Contrarily, `os.path.lexists(path)` will "Return True if path refers to an existing path. Returns True for broken symbolic links." When I tried to use `os.path.lexists(path)` to check the existence of the shell in `get_shell()`, Tern in a container properly located the shell and used it to collect package information. For now, I think using `os.path.lexists` to check for the existence of a shell makes sense since it still properly checks for the existence of the file, but ignores Alpine's broken symlinks when running Tern from a container.

I am going to spend a little more time on this trying to figure out why the Alpine symlinks work when I run Tern natively on my Ubuntu VM but then break when running Tern from a photon or debian-based container. It could be that the tern container image is missing a necessary dependency and we don't need to go with the lexists workaround mentioned above.

**Comment by rnjudge** [comment]
Yep, busybox was missing from Tern's container image. Once that dependency is installed then the shell is found just fine for Alpine. @nishakm Since I am re-doing the Dockerfile for Tern anyway, I am thinking I will just install busybox as part of the dependencies instead of using `lexist` to check for the shell path. Thoughts?

**Comment by nishakm** [comment]
> Yep, busybox was missing from Tern's container image. Once that dependency is installed then the shell is found just fine for Alpine. @nishakm Since I am re-doing the Dockerfile for Tern anyway, I am thinking I will just install busybox as part of the dependencies instead of using `lexist` to check for the shell path. Thoughts?

I'd rather depend on busybox existing in the Alpine image. Is it possible to follow the symlink to the correct binary?

**Comment by nishakm** [comment]
Maybe `os.path.realpath()`?

**Comment by rnjudge** [comment]
> Maybe `os.path.realpath()`?

I tried this, but doesn't work :/

**Comment by rnjudge** [comment]
The issue is due to the fact that the `bin/sh` symlink points to an absolute `/bin/busybox` path which is in the root of the container, not the root of the working directory where it checks for the existence of the path. To avoid adding busybox to Tern's container image, we will need to add functionality that can resolve the absolute path links to the path that actually exists inside the container.
