### ISSUE TITLE
setup.py  install failed?

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#783]
(scanvenv) [root@localhost tern-master]# python setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/hf/scanvenv/lib64/python3.6/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/hf/scanvenv/lib64/python3.6/site-packages/pbr/util.py", line 271, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/hf/scanvenv/lib64/python3.6/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/hf/scanvenv/lib64/python3.6/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/hf/scanvenv/lib64/python3.6/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/hf/scanvenv/lib64/python3.6/site-packages/pbr/packaging.py", line 876, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name tern was given, but was not able to be found.
error in setup command: Error parsing /home/hf/tern-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name tern was given, but was not able to be found.

**Comment by rnjudge** [comment]
This seems like an environment issue, not an issue with Tern. I can't reproduce this and the command works fine for me. If you are trying to get the dist tarball you could also try `python setup.py sdist` instead. Or perhaps try re-cloning Tern from the tip of master and maybe that will fix your problem? Are all your dependencies installed and up to date?

```
(ternenv) rjudge:tern$ python setup.py install
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.1s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.1s)
running build
running build_py
running egg_info
writing tern.egg-info/PKG-INFO
writing dependency_links to tern.egg-info/dependency_links.txt
writing entry points to tern.egg-info/entry_points.txt
writing requirements to tern.egg-info/requires.txt
writing top-level names to tern.egg-info/top_level.txt
writing pbr to tern.egg-info/pbr.json
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
writing manifest file 'tern.egg-info/SOURCES.txt'
running install_lib
running install_egg_info
removing '/home/rjudge/ternenv/lib/python3.6/site-packages/tern-2.1.1.dev44.egg-info' (and everything under it)
Copying tern.egg-info to /home/rjudge/ternenv/lib/python3.6/site-packages/tern-2.1.1.dev44.egg-info
running install_scripts
Installing tern script to /home/rjudge/ternenv/bin
```

**Comment by 00032118** [comment]
Thank you for your prompt reply. I have solved this problem. It may be due to different versions of pbr. After I added a matadata file to the directory, the problem was solved.
