### ISSUE TITLE
How do cve-bin-tool, claire, and trivy compare?

### ISSUE THREAD

**Issue by westurner** [tern-tools/tern#794]
How do cve-bin-tool, claire, and trivy compare?

- https://github.com/tern-tools/tern#cve-bin-tool
  - https://github.com/intel/cve-bin-tool
- https://github.com/coreos/clair
- https://github.com/aquasecurity/trivy

**Comment by nishakm** [comment]
:wave: You should ask this question on https://github.com/intel/cve-bin-tool. My understanding is that clair is not shipped as a standalone executable package but as a container image. Not sure about trivy.

**Comment by westurner** [comment]
FWIU, Clair and Trivy are significantly more comprehensive vuln scanners?

This is relevant to tern because tern could rely upon more comprehensive tools?

**Comment by nishakm** [comment]
Clair is built to scan container images for vulnerabilities. It's already widely used. Tern isn't quite in that space - it's a container package inventory tool and SBoM generator. However, it's flexible enough you can attach a file vuln scanner to it. That's what cve-bin-tool is. You can attach a more comprehensive vuln scanner to it if you want. You will have to create a plugin for it.
