### ISSUE TITLE
Extra "1"s printed in json output

### ISSUE THREAD

**Issue by tevoinea** [tern-tools/tern#796]
**Describe the bug**
When scanning `node:slim` on Windows using tern 2.2.0 (and master), piping stdout produces 2 "1"s and then the json string. This doesn't happen on golang:alpine though.

**To Reproduce**
Steps to reproduce the behavior (on a Windows machine):
1. `git clone https://github.com/tern-tools/tern.git`
2. ` docker build -t ternd .`
3. `docker run --privileged --device /dev/fuse -v /var/run/docker.sock:/var/run/docker.sock --rm ternd report -f json -i node:slim > output.json`
4. Open `output.json`

See this: 
![image](https://user-images.githubusercontent.com/58236992/92044813-e340a100-ed33-11ea-98d2-bdac7f40c000.png)

**Expected behavior**
`output.json` contains valid json

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version' tern 2.2.0
- Operating System Windows Version 10.0.19041 Build 19041
- Container OS node:slim
- Python version 3.7.9

**Please attach files if they exist**
- tern.log
- report.*

**Comment by nishakm** [comment]
@tevoinea I tried this at the tip of master and I am unable to recreate the issue. Could you try as well? Please run `docker build -t ternd -f ci/Dockerfile .` at the tip of master and then try. Thanks for filing the issue!

**Comment by tevoinea** [comment]
@nishakm I was able to verify the "1"s are gone after building the tip of master using the python tooling/instructions from CONTRIBUTING.md!
