### ISSUE TITLE
Tern cannot retrieve full image metadata

### ISSUE THREAD

**Issue by moisesdelacruz301997** [tern-tools/tern#800]
Using `tern report -o output.txt -i debian:buster` displays error messages and tern wasn't able to generate the report.
![Screen Shot 2020-09-07 at 9 36 12 AM](https://user-images.githubusercontent.com/58415523/92340594-940cbe80-f0ed-11ea-82aa-3a738e3a4285.png)

**To Reproduce**
Download latest release [here](https://github.com/tern-tools/tern/releases/tag/v2.2.0).

Follow steps stated in [Getting Started on Linux](https://github.com/tern-tools/tern#getting-started-on-linux)

Run ` tern --version`

You'll get

`Tern version 2.2.0
   python version = 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) `

Then run `tern report -o output.txt -i debian:buster` and the error message should display.

I marked this Issue as a question because as per checking the logs, you can see `Command failed. 'getfattr' not found on system.` so I think that I did the something wrong in my installation.

But as per installing tern in pip, I get this.

![Screen Shot 2020-09-07 at 9 41 48 AM](https://user-images.githubusercontent.com/58415523/92340838-5e1c0a00-f0ee-11ea-8fab-f939b1364de9.png)

Thanks in advanced!

**Comment by nishakm** [comment]
👋 You will need to install some system requirements: git, attr, python and pip. Looks like you didn't install attr.

**Comment by moisesdelacruz301997** [comment]
Hi, I have tried several steps to install attr but it seems like it is not supported on my machine. Is it compatible with MacOS Catalina(10.15.6)? Or attr is installation is different for Mac?

**Comment by nishakm** [comment]
> Hi, I have tried several steps to install attr but it seems like it is not supported on my machine. Is it compatible with MacOS Catalina(10.15.6)? Or attr is installation is different for Mac?

Oh, I'm sorry, I missed that detail. If you are running on macOS, you can run it using Docker: https://github.com/tern-tools/tern#getting-started-with-docker

**Comment by moisesdelacruz301997** [comment]
So that's it, cool! Thank you so much.
