### ISSUE TITLE
The big code refactor

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#801]
**Description**
Several features requested by our community can be enabled easily if we re-organize the code base. This would also make it easier to write tests for it and increase our code coverage, not to mention making the code readable and help us solve a good number of our technical debt issues.

This is a super issue. A number of issues will be created that will link here.

**Sub Issues**
#802
#803 
#804
#807 
#808
#811

**Comment by emaanhaseem** [comment]
I and a small group of students from a UT Austin CS Virtualization class would like to claim this issue and tackle it.

**Comment by nishakm** [comment]
> I and a small group of students from a UT Austin CS Virtualization class would like to claim this issue and tackle it.

Super appreciate you for offering to tackle this! It's a tricky one and time sensitive (like the end of September!). I wonder maybe if you are looking for something more long term?

**Comment by emaanhaseem** [comment]
Thanks for letting us know the time sensitivity! Is there an issue you'd recommend that is more long term? For example to be completed by the end of the year. Thanks again.

**Comment by nishakm** [comment]
> Thanks for letting us know the time sensitivity! Is there an issue you'd recommend that is more long term? For example to be completed by the end of the year. Thanks again.

We have a number of bugs due by next release: https://github.com/tern-tools/tern/milestone/13. Definitely try one of those. I will be filing more issues that you can take on. Let me know which ones you would like to take on.

**Comment by nishakm** [comment]
All relevant issues are closed.
