### ISSUE TITLE
Move operations on raw image tarball into `load` folder

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#811]
**Description**
Currently checking an input tarball and extracting it into a directory are merged in the `extract_image_metadata` function. However, the tarball may be in schema 1 or schema 2 or some other kind of output. So it makes sense to move these various checks into a new file `tern/load/raw.py`.

**To Do**
This is dependent on #802 i.e. creating a folder called `load`.

**Super Issues**
#802

**Comment by m1-key** [comment]
@nishakm I guess now after few code refactorings, there is no function named `extract_image_metadata`. So now which function is to be moved in `tern/load/raw.py`? Also, I found two functions named `extract_image` in `image.py` and `extract_tarfile` in `tern/utils/rootfs.py` which might be the one I should look for to solve the above issue.

**Comment by m1-key** [comment]
@nishakm any update on this ?

**Comment by nishakm** [comment]
Oh I thought this was closed. Thanks for taking a look! I will close this now.
