### ISSUE TITLE
Error when generating report for some docker images

### ISSUE THREAD

**Issue by michellegx111** [tern-tools/tern#812]
I have tried to run tern in docker to analyse my docker images. For some, it run successfully, but for others it failed with message "ERROR - rootfs - Command failed. /bin/sh: 1: export: 2A684B57436A81FA8706B53C61C3351A438A3B7D: bad variable name
"

Does anyone know why I have such error for some of my docker images? Thanks a lot in advance!

The whole log are in the attachment.
[error.txt](https://github.com/tern-tools/tern/files/5268262/error.txt)

**Comment by nishakm** [comment]
It looks like our parser is ignoring the tabs in one of the ENV lines:
```
ENV JETTY_GPG_KEYS \
	# Jan Bartel      <janb@mortbay.com>
	AED5EE6C45D0FE8D5D1B164F27DED4BF6216DB8F \
	# Jesse McConnell <jesse.mcconnell@gmail.com>
	2A684B57436A81FA8706B53C61C3351A438A3B7D \
	# Joakim Erdfelt  <joakim.erdfelt@gmail.com>
	5989BAF76217B843D66BE55B2D0E1FB8FE4B68B4 \
	# Joakim Erdfelt  <joakim@apache.org>
	B59B67FD7904984367F931800818D9D68FB67BAC \
	# Joakim Erdfelt  <joakim@erdfelt.com>
	BFBB21C246D7776836287A48A04E0C74ABB35FEA \
	# Simone Bordet   <simone.bordet@gmail.com>
	8B096546B1A8F02656B15D3B1677D141BCF3584D \
	# Greg Wilkins    <gregw@webtide.com>
	FBA2B18D238AB852DF95745C76157BDF03D0DCD6 \
	# Greg Wilkins    <gregw@webtide.com>
	5C9579B3DB2E506429319AAEF33B071B29559E1E \
	# Olivier Lamy <olamy@apache.org>
	F254B35617DC255D9344BCFA873A8E86B4372146
```
@ForgetMe17 Do you know of a fix for this?
