### ISSUE TITLE
Tern crashes when no copyright file exists

### ISSUE THREAD

**Issue by pilvikala** [tern-tools/tern#822]
I am getting the following error when running a scan (command `tern report -o output.txt -i fossid-nginx:2020.2`):
```
ERROR - rootfs - Command failed. /bin/cat: /usr/share/doc/fossid-release/copyright: No such file or directory
```

Does tern expect a copyright file somewhere in the container?

**Comment by nishakm** [comment]
> Does tern expect a copyright file somewhere in the container?

One kind of metadata tern looks for is copyrights. The typical place for a Debian style OS's copyright files is `/usr/share/doc`. It looks like there isn't a copyright file in that location for your specific image. It's not a bug or critical error but it's something someone who is doing license compliance should take note of.

**Comment by pilvikala** [comment]
Thanks for the explanation. The issue is that it appears tern actually crashes without producing any output because of this issue.

**Comment by nishakm** [comment]
> Thanks for the explanation. The issue is that it appears tern actually crashes without producing any output because of this issue.

OK, that is not supposed to happen. I will check.

**Comment by nishakm** [comment]
@pilvikala I am not able to access the image you used. Is there a public equivalent?

**Comment by pilvikala** [comment]
> @pilvikala I am not able to access the image you used. Is there a public equivalent?

Not really, but I'll try to create a minimal sample that should be similar.

**Comment by pilvikala** [comment]
The package attached contains a Dockerfile that you can build and a dummy debian package that is needed for the build and that causes the failure.

[tern.zip](https://github.com/tern-tools/tern/files/5530603/tern.zip)

The command that I ran with tern was 

`tern report -o output.txt -i package-that-breaks-tern:latest`

I also discovered an interesting thing: If I change the line 4 in the Dockerfile to install the package using `apt` (not the `apt-get`), tern does not fail.

**Comment by nishakm** [comment]
@pilvikala Thanks for helping me fix this issue.
