### ISSUE TITLE
Suggest a different name for -d/--driver command line option

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#824]
**Problem Statement**
`-d` is the short version for `--dockerfile` and is the same for `--driver`. This may cause confusion

**Describe the Proposal**
Perhaps change it to `-dr` instead of `-d`.

**Steps to Implement Proposal**
Simply replace this line in `tern/__main__.py`:
```
122     parser.add_argument('-d', '--driver', metavar="DRIVER_OPTION",    <-- replace -d with -dr          
123                         help="Required when running Tern in a container."       
124                         "Using 'fuse' will enable the fuse-overlayfs driver "   
125                         "to mount the diff layers of the container. If no "     
126                         "input is provided, 'fuse' will be used as the "        
127                         "default option.")      
```

**Comment by LucianTavares** [comment]
> **Declaração do problema**
> `-d` é a versão resumida de `--dockerfile`e o mesmo para `--driver`. Isso pode causar confusão
> 
> **Descreva a proposta**
> Talvez altere para em `-dr`vez de `-d`.
> 
> **Etapas para implementar a proposta**
> Basta substituir esta linha em `tern/__main__.py`:
> 
> ```
> 122     parser.add_argument('-d', '--driver', metavar="DRIVER_OPTION",    <-- replace -d with -dr          
> 123                         help="Required when running Tern in a container."       
> 124                         "Using 'fuse' will enable the fuse-overlayfs driver "   
> 125                         "to mount the diff layers of the container. If no "     
> 126                         "input is provided, 'fuse' will be used as the "        
> 127                         "default option.")      
> ```

Uma sugestão para a solução seria:

'--driver' = '-dri'
'--dockerfile' = '-dockf'

**Comment by nishakm** [comment]
This issue was fixed. Sorry!
