### ISSUE TITLE
Consolidate common code used by container/run.py and dockerfile/run.py

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#825]
**Description**
There are some steps in common between `container/run.py` and `dockerfile/run.py`. These can be consolidated in one function and placed in `tern/analyze/default/core.py`.

**To Do**
1. Find the steps that are common
2. Place the steps in a function in `core.py`
3. Change imports in `container/run.py` and `dockerfile/run.py`
4. Run functional tests

**Super Issues**
#801

**Comment by m1-key** [comment]
@nishakm I am looking forward to solving this issue. I was reading the code of both files. What I found that we can use the container/run.py functions at some places. Like cleanup and saving to the cache was there in dockerfile/run.py, for that we can use directly teardown function of container/run.py. Similarly, at one-two places, we can do the same.

**Comment by nishakm** [comment]
Thanks @m1-key! Could you post a list of things you would be changing? I haven't looked at this in a while now :)

**Comment by m1-key** [comment]
> Thanks @m1-key! Could you post a list of things you would be changing? I haven't looked at this in a while now :)

Till now I have found that in container/run.py we have a function named ```execute_image``` which is doing the same thing as done by two functions combined in dockerfile/run.py namely ```full_image_analysis``` and ```analyze_full_image```.
I have shared a screenshot of the same. As you can see the same sequence of instructions has been followed. So rather than having this, we can use the ```execute_image``` function itself with slight modifications. 

![WhatsApp Image 2021-02-23 at 21 27 07](https://user-images.githubusercontent.com/39923784/108870215-ed29c980-761d-11eb-9aa2-0b80aa3de5c2.jpeg)


![WhatsApp Image 2021-02-23 at 21 26 00](https://user-images.githubusercontent.com/39923784/108870278-fa46b880-761d-11eb-8f5f-7b17794dfc8b.jpeg)

**Comment by nishakm** [comment]
@m1-key The trouble with using `execute_image` as part of `execute_dockerfile` is that the number of checks you will need to make sure the right arguments are passed in and out based on whether you are providing an image or a dockerfile is so much that it increases complexity. This was how `execute_image` was before (it was just called `execute` back then). The splitting of the execution paths reduced complexity and helps us target the right code blocks for the right concern. Can you identify any repeat procedures that can be moved into their own function, maybe under `default_common` that can be called in `execute_image` and `execute_dockerfile`?

Also, `analyze_full_image` and `full_image_analysis` are kindof ambiguous names. We would want to rename them to something else. Let me think on this one.

**Comment by m1-key** [comment]
> @m1-key The trouble with using `execute_image` as part of `execute_dockerfile` is that the number of checks you will need to make sure the right arguments are passed in and out based on whether you are providing an image or a dockerfile is so much that it increases complexity. This was how `execute_image` was before (it was just called `execute` back then). The splitting of the execution paths reduced complexity and helps us target the right code blocks for the right concern. Can you identify any repeat procedures that can be moved into their own function, maybe under `default_common` that can be called in `execute_image` and `execute_dockerfile`?
> 
> Also, `analyze_full_image` and `full_image_analysis` are kindof ambiguous names. We would want to rename them to something else. Let me think on this one.

Yes, the procedures that are common: - `setup`,`cimage.analyze`,`cleanup` and `save_to_cache`. 
As `execute_dockerfile` calls `analyze_single_dockerfile` which calls `full_image_analysis` and this calls `analyze_full_image`. Now `analyze_full_image` has above-mentioned procedures. Also `execute_image` has these procedures. So we can move them into single common function.
Putting them into a single function i.e `default_common` will get rid of the function `analyze_full_image` also.

**Comment by m1-key** [comment]
`default_common` would look like this : 
![Screenshot_31](https://user-images.githubusercontent.com/39923784/108882776-c756f180-762a-11eb-8726-9b88be745a11.png)

**Comment by m1-key** [comment]
@nishakm I made this function which has all the procedures which are common in `container/run.py` and `dockerfile/run.py`.
I have used the following arguments: - 
`image:- Basically it is the image object.`
`redo, driver, extension:- Same as described in the main file`
`args:- It is used because we have to pass the args to report in order to generate the report`
`image_file:- This is a boolean which tells whether the function has been called from execute_image or execute_dockerfile`
```
def default_common_procedure(image, redo, driver, extension, args=None, image_file=False):
    """Setup the image object and anything else for analysis"""
    # Add a Notice object for each layer
    for layer in image.layers:
        origin_str = 'Layer {}'.format(layer.layer_index)
        layer.origins.add_notice_origin(origin_str)
    # Set up working directories and mount points
    rootfs.set_up()
    # analyze the image
    cimage.analyze(image, redo, driver, extension)
    if image_file:
        report.report_out(args, image)
    # Add the image layers to the cache
    common.save_to_cache(image)
    # Clean up working directories and mount points
    rootfs.clean_up()
```

**Comment by nishakm** [comment]
Closing this issue: https://github.com/tern-tools/tern/pull/892#issuecomment-792945212

The two use cases are different enough that we can't do any more consolidation without un-separating the two concerns in the code base.
