### ISSUE TITLE
Add new option '-l,--live' to 'report' subcommand

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#852]
**Description**
Add a new subcommand `-l,--live` to `report` subcommand

**Implementation**
in `tern/__main__.py`, add subparser option under:
```
# subparser for report
```

It should look like this:
```                                 
parser_report.add_argument('-l', '--live', action='store_true', 
                                help="Generate a report for the current state of the filesystem. "
                                          "This is useful when running Tern in a new namespace or VM.")                                                                                 
```

**Super Issues**
#850

**Comment by aalexanderr** [comment]
doesn't this conflict with #845   ?

**Comment by sankalpmukim** [comment]
Why is this issue still open? Is there a problem with @m1-key 's commit?

**Comment by m1-key** [comment]
> Why is this issue still open? Is there a problem with @m1-key 's commit?

No, the functionality that is required to run with this command is in progress, on later stage when all the functionalities of live container are implemented then I guess it will be merged. Since it is WIP that's why it is on hold.

**Comment by rnjudge** [comment]
@nishakm Ok to close this issue?

**Comment by nishakm** [comment]
Huh...I guess with a merge request the issues referenced in the commit messages don't automagically close. I'll close it.
