### ISSUE TITLE
Implement analyzing a live container

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#858]
**Description**
In `tern/analyze/default/container/single_layer.py` there is a function called `analyze_first_layer` which takes in an `Image` object, a master list of `Package` objects, and a redo boolean. Implement a `analyze_live` function which takes just an `ImageLayer` object and returns a populated object from `core.execute_base` after discovering a shell and a binary from the command library.

**Background**
This needs to be implemented before #853.

**Super Issues**
#850

**Comment by m1-key** [comment]
@nishakm Do I need to check whether the ImageLayer given in the argument can be loaded by cache or not?

**Comment by nishakm** [comment]
> @nishakm Do I need to check whether the ImageLayer given in the argument can be loaded by cache or not?

`core.execute_base` should take care of that

**Comment by m1-key** [comment]
> > @nishakm Do I need to check whether the ImageLayer given in the argument can be loaded by cache or not?
> 
> `core.execute_base` should take care of that

I have opened a PR for this issue.

**Comment by nishakm** [comment]
Closing this issue and creating new ones to address it.
