### ISSUE TITLE
Enable inventory of Distroless images

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#864]
**Describe the Feature**
Distroless provides runtime container images. It doesn't have a shell and therefore not as straightforward to enable inventorying via a binary. However, there is a manifest within the rootfs that can read, so inventorying can still be done.

**Use Cases**
See https://github.com/ossf/wg-digital-identity-attestation/issues/20
We also have difficulty running file level static analysis to get an SBoM for this kind of rootfs, so a deterministic method would be very useful.

**Implementation Changes**
See comment: https://github.com/ossf/wg-digital-identity-attestation/issues/20#issuecomment-724091084

The "host" method invokes a host command or script on the working directory without the `unshare -pf` which you would get from the `invoke_in_chroot`.

**Comment by JamieMagee** [comment]
From looking at the referenced comment, I think a sample script would be something like:

```sh
files=$(ls var/lib/dpkg/status.d)
for f in $files; do grep -oP "^Package: \K.*$" var/lib/dpkg/status.d/$f; done
```

Running this in an unpacked layer of `gcr.io/distroless/base-debian10` yields

```
libc6
libssl1.1
openssl
```

and the version equivalent

```sh
for f in $files; do grep -oP "^Version: \K.*$" var/lib/dpkg/status.d/$f; done
```

yields

```
2.28-10
1.1.1d-0+deb10u5
1.1.1d-0+deb10u5
```

etc. for the other commands.

**Comment by JamieMagee** [comment]
@nishakm I've been looking into implementing this. You mentioned about using the `host` method to invoke commands, and the documentation also says this:

https://github.com/tern-tools/tern/blob/11fc8a33eb52eb8ebdb17e14b80bf3605160bd7a/tern/analyze/default/command_lib/base.yml#L12-L17

However, the implementation only appears to be there for `container`, and `host` is missing?

https://github.com/tern-tools/tern/blob/11fc8a33eb52eb8ebdb17e14b80bf3605160bd7a/tern/report/content.py#L78-L87

**Comment by nishakm** [comment]
@JamieMagee What I meant was that `host` is meant to be one of ways tern can run scripts (and something that I had implemented a long long time ago and since removed from the code base) but the execution path is not implemented yet.

The place to implement this is in https://github.com/tern-tools/tern/blob/main/tern/analyze/default/collect.py#L22
and in https://github.com/tern-tools/tern/blob/main/tern/analyze/default/collect.py#L60

Here we also need to add a new function `invoke_on_host` which just execs the above scripts wherever tern is currently running. Now this is going to be really tricky on Windows and Mac hosts because we are now relying on the host's shell rather than the container's shell. I'm open to ideas on how to tackle this :)

**Comment by JamieMagee** [comment]
@nishakm I think we're on the same page. It wasn't clear to me whether `invoke_on_host` had yet to be implemented or had been removed in a refactor. Regardless, it needs to be implemented now.

As for the issue of Windows and Mac hosts, I would defer that question for now and assume that we have a Linux host. Let's get something working first, then worry about crossplatform support afterwards.

**Comment by JamieMagee** [comment]
It's hacked together right now, but I've proven the concept:

```
Docker image: gcr.io/distroless/base@sha256:dd04859fc2fd78672388a1f60a0ddc935bf7c365279c14f7533606ffc9d446be:
        Layer 1:
                warning: No known shell found in image. Cannot invoke commands

                warning: Unable to find a known package manager. Cannot list packages.

                info: Found 'Distroless' in /etc/os-release.
        File licenses found in Layer:  None
        Packages found in Layer:  base-files-9.9+deb9u13, netbase-5.4, tzdata-2021a-0+deb9u1
        Licenses found in Layer:  None
```

**Comment by nishakm** [comment]
@rnjudge I think we may remove the distroless issue from GSoC? What do you think we can substitute it with?

**Comment by nishakm** [comment]
> It's hacked together right now, but I've proven the concept:
> 
> ```
> Docker image: gcr.io/distroless/base@sha256:dd04859fc2fd78672388a1f60a0ddc935bf7c365279c14f7533606ffc9d446be:
>         Layer 1:
>                 warning: No known shell found in image. Cannot invoke commands
> 
>                 warning: Unable to find a known package manager. Cannot list packages.
> 
>                 info: Found 'Distroless' in /etc/os-release.
>         File licenses found in Layer:  None
>         Packages found in Layer:  base-files-9.9+deb9u13, netbase-5.4, tzdata-2021a-0+deb9u1
>         Licenses found in Layer:  None
> ```

@JamieMagee Feel free to submit a PR with what you have. I can either review it with changes or work on top of it. Whatever works for you.

**Comment by rnjudge** [comment]
> @rnjudge I think we may remove the distroless issue from GSoC? What do you think we can substitute it with?

@nishakm https://github.com/tern-tools/tern/issues/757?

**Comment by nishakm** [comment]
> > @rnjudge I think we may remove the distroless issue from GSoC? What do you think we can substitute it with?
> 
> @nishakm #757?

https://github.com/tern-tools/tern/wiki/Google-Summer-of-Code-2021-Ideas#enable-inventory-of-distroless-container-images-beginnerintermediate
