### ISSUE TITLE
Reduce complexity of analyze_subsequent_layers()

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#868]
**Description**
analyze_subsequent_layers() has 5 arguments. This is an issue if we ever want to add more command line arguments in the future that need to be passed to the layer analysis, as prospector will complain when there are more than 5 arguments.

**To Do**
Create a new file, `options.py` in `tern/analyze`. Create an `Options` class in options.py. Instead of passing all the command line arguments individually to the analyze functions, create an options object to hold them all.

**Background**
This will make implementing analysis related work easier, like #840.

**Comment by nishakm** [comment]
@rnjudge what do you think of just passing `args` instead of creating a different options object?
