### ISSUE TITLE
Scan fail with images that doesn't have repositories and tags

### ISSUE THREAD

**Issue by jcfiorenzano** [tern-tools/tern#874]
**Describe the bug**
When the scanning is executed using the imageId on an image that doesn't have RepoDigest and RepoTags then tern fails with the following exception .
```
local variable \'image_string\' referenced before assignment
```
I tried the same image using tern 2.0.0 and it scanned the image properly.

**To Reproduce**
1. Build an image without specifying repository and tag `docker build .`
2. Scan the resulting image using the imageId

**Error in terminal**
```
{ memoryInfo:
   '{"rss":39120896,"heapTotal":9961472,"heapUsed":5357888,"external":8962}',
  errorCode: 1,
  errorSignal: null,
  errorMessage:
   'Traceback (most recent call last):\n  File "/usr/local/bin/tern", line 8, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python3.7/dist-packages/tern/__main__.py", line 192, in main\n    do_main(args)\n  File "/usr/local/lib/python3.7/dist-packages/tern/__main__.py", line 95, in do_main\n    crun.execute_image(args)\n  File "/usr/local/lib/python3.7/dist-packages/tern/analyze/default/container/run.py", line 73, in execute_image\n    image_string = extract_image(args)\n  File "/usr/local/lib/python3.7/dist-packages/tern/analyze/default/container/run.py", line 40, in extract_image\n    return image_string\nUnboundLocalError: local variable \'image_string\' referenced before assignment\n',
  outputString: '',
  exception: undefined }
```

**Expected behavior**
The image is scanned properly

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version': 2.3.0
- Operating System: Windows 10 19042.746 and Ubuntu 20.04.1
- Python version 3.7

**Comment by nishakm** [comment]
@jcfiorenzano I believe we changed the CLI to expect an image of the form `image:tag` or `image@digest_type:digest`, but you shouldn't be getting this error if you enter something else, I will take a look.

**Comment by nishakm** [comment]
@jcfiorenzano I am unable to reproduce the error at the tip of main:
```
$ tern report -i d7b047f41ea7
2021-02-08 09:18:12,996 - DEBUG - __main__ - Starting...
2021-02-08 09:18:12,997 - DEBUG - prep - Setting up...
2021-02-08 09:18:13,080 - CRITICAL - __main__ - Unsupported image string format.
Please provide string in image:tag or image@digest_type:digest format.
```

**Comment by jcfiorenzano** [comment]
Hi @nishakm in the following screenshot you can see all the steps that I followed
![image](https://user-images.githubusercontent.com/5582507/107311084-924f7a00-6a42-11eb-8f2c-3d987ba3bdd2.png)
the OS is Ubuntu 20.04
here is the screenshot with the `docker  inspect` results
![image](https://user-images.githubusercontent.com/5582507/107311550-62ed3d00-6a43-11eb-9fd0-7137884c5bb6.png)

**Comment by jcfiorenzano** [comment]
If this is fixed at the tip of main, is there any possibility of releasing a patch for tern 2.3.0?

**Comment by nishakm** [comment]
> If this is fixed at the tip of main, is there any possibility of releasing a patch for tern 2.3.0?

@rnjudge WDYT? It's a pretty serious bug IMHO.

**Comment by rnjudge** [comment]
@nishakm I am not opposed to a patch, especially if release 3.0.0 gets pushed closer to April. I am trying to find the patch that fixed this, however. It looks like a [commit](https://github.com/tern-tools/tern/commit/222a1388f37348617bff36bdc1aab4ab9701e259) was added in 2.3.0 that supposedly addressed this issue but I don't see the fix since 2.3.0 that is the clear fix (granted, I have not spent more than 10 mins looking).

**Comment by jcfiorenzano** [comment]
Hi is there any update on this?

**Comment by rnjudge** [comment]
@jcfiorenzano thanks for your patience on this. This is not actually fixed at the tip of main and I can reproduce the error you're seeing. Here's the part of the code where it's failing currently. In the example you shared above, `image_attrs['RepoDigests']` and `image_attrs['RepoTags']` don't exist so the `image_string` value never gets set which is what is causing the error. 

```
if args.docker_image:
        # extract the docker image
        image_attrs = docker_api.dump_docker_image(args.docker_image)
        if image_attrs:
            # repo name and digest is preferred, but if that doesn't exist
            # the repo name and tag will do
            if image_attrs['RepoDigests']:
                image_string = image_attrs['RepoDigests'][0]
            if image_attrs['RepoTags']:
                image_string = image_attrs['RepoTags'][0]
            return image_string
```


The way that you specified the image on the command line is perfectly acceptable to Tern currently if `RepoDigests` or `RepoTags` exist in the Docker image metadata. If I run the same command you did with an image that has the Tag and Digest value, Tern runs fine. 
```
(ternenv) rjudge:tern$ tern report -i sha256:7bd0475720af2735ae02771ba8f7d635a59c9f553a7736eefbfccf87474a35ce
2021-02-16 20:30:26,035 - DEBUG - __main__ - Starting...
2021-02-16 20:30:26,036 - DEBUG - prep - Setting up...
021-02-16 20:30:27,392 - DEBUG - run - Starting analysis...
2021-02-16 20:30:27,412 - DEBUG - docker_api - Checking if image "sha256:7bd0475720af2735ae02771ba8f7d635a59c9f553a7736eefbfccf87474a35ce" is available on disk...
2021-02-16 20:30:27,415 - DEBUG - docker_api - Image "sha256:7bd0475720af2735ae02771ba8f7d635a59c9f553a7736eefbfccf87474a35ce" found

```

If I run the same command with an image that is missing those values, I see the same "local variable references before assignment" error you are seeing.. I'm working on a fix for the issue now. Thanks for finding it!

**Comment by rnjudge** [comment]
@nishakm I think that using the docker image `Id` as a fallback when no `RepoDigest` or `RepoTag` is appropriate.

**Comment by rnjudge** [comment]
@jcfiorenzano [tern 2.4.0 is available](https://pypi.org/project/tern/2.4.0/) with this patch. Thanks for reporting!
