### ISSUE TITLE
Notices are missing in the default report when cache is populated

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#875]
**Describe the bug**
If you run Tern on an image when the cache has already been populated with information about that image, notices are missing from the default report. This includes the base OS information. From what I can tell, this is only an issue with the default report but have not tested all the formats yet. By notices, I mean that the following information is missing when Tern loads layers from the cache:

```
		info: Found 'VMware Photon OS/Linux' in /etc/os-release.
		info: Retrieved by invoking listing in command_lib/base.yml
names:
	in container:
	tdnf check-update > /dev/null
	tdnf list installed | cut -f1 -d"."

licenses:
	in container:
	tdnf check-update > /dev/null
	pkgs=`tdnf list installed | cut -f1 -d"."`
	for p in $pkgs; do tdnf info $p | head -10 | tail -1 | cut -f2 -d":" | xargs; done

proj_urls:
	in container:
	tdnf check-update > /dev/null
	pkgs=`tdnf list installed | cut -f1 -d"."`
	for p in $pkgs; do tdnf info $p | head -9 | tail -1 | cut -f2-3 -d":" | xargs; done


versions:
	in container:
	tdnf check-update > /dev/null
	list=`tdnf list installed`
	c=0; for l in $list; do if [ $c == 1 ]; then echo $l; fi; c=$(((c+1)%3)); done;



		warning: No listing method for 'copyrights'. Additional analysis may be required.
No listing method for 'srcs'. Additional analysis may be required.



```

Related: #752 #823 

**To Reproduce**
1. Run tern on any image with a fresh cache (i.e. `tern -c`; `tern report -i photon:3.0`)
2. Now that the cache is populated, run the same report collection: `tern report -i photon:3.0`
3. Look at the output report. The notices are missing from the report.

**Expected behavior**
The notices should be there.

**Environment you are running Tern on**
Running at tip of `main`
https://github.com/tern-tools/tern/commit/4a820cfa294ed44614b4928aca8fff450a26e650

**Comment by nishakm** [comment]
@rnjudge Confirmed the issue exists on `main`. Do you want me to work on this?

**Comment by rnjudge** [comment]
@nishakm That would be great! There are a few bugs related to this that you may or may not want to address at the same time. I don't expect you to fix all at the same time, just for your consideration: #752 #823

**Comment by nishakm** [comment]
Looks like all that information is not recorded at all.

**Comment by rnjudge** [comment]
> Looks like all that information is not recorded at all.

I hadn't noticed this before. Perhaps something got shifted in the refactor?
