### ISSUE TITLE
Debian dockerfile reports duplicate packages

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#899]
**Describe the bug**
When Tern runs with the following debian dockerfile, it reports duplicate packages in the second layer when it loads from the cache. If it's not loading from the cache, Tern properly reports the packages in the second layer.

```
FROM debian:jessie
RUN apt-get update && apt-get install -y vim && apt-get clean
```

**To Reproduce**
1. Clear the cache and run `tern -d samples/debian_vim/Dockerfile`, see the correct reporting in the second layer.
2. Run `tern -d samples/debian_vim/Dockerfile` again and see duplicate packages reported in the second layer.

**Expected behavior**
This is what I expect in the second layer:
```
	File licenses found in Layer:  None
	Packages found in Layer:  libgpm2-1.20.4-6.1+b2, vim-2:7.4.488-7+deb8u4, vim-common-2:7.4.488-7+deb8u4, vim-runtime-2:7.4.488-7+deb8u4

```

**Environment you are running Tern on**
The error exists in as early as 2.3.0. When I tested with 2.2.0 I got the following error which makes me think that there's an isssue in the way the master list is updated when consulting the cache.
```
  File "/home/rjudge/testrel/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/__main__.py", line 204, in main
    do_main(args)
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/__main__.py", line 92, in do_main
    run.execute_dockerfile(args)
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/analyze/docker/run.py", line 136, in execute_dockerfile
    analyze(full_image, args, dfile_lock, dfobj)
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/analyze/docker/run.py", line 70, in analyze
    args.driver)
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/analyze/docker/analyze.py", line 43, in analyze_docker_image
    dfile_lock, driver)
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/analyze/docker/analyze.py", line 188, in analyze_subsequent_layers
    common.update_master_list(master_list, image_obj.layers[curr_layer])
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/analyze/common.py", line 575, in update_master_list
    if item.is_equal(pkg):
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/classes/package.py", line 200, in is_equal
    other_pkg_dict = other.to_dict()
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/classes/package.py", line 139, in to_dict
    file_list = [f.to_dict(template) for f in self.__files]
  File "/home/rjudge/testrel/lib/python3.6/site-packages/tern/classes/package.py", line 139, in <listcomp>
    file_list = [f.to_dict(template) for f in self.__files]
AttributeError: 'dict' object has no attribute 'to_dict'
```

**Comment by rnjudge** [comment]
The reason that a handful of duplicated packages are appearing in the output file when Tern pulls from the cache has to do with a failing `is_equal` check to see if the layer package already exists on the master list in `update_master_list()` (line 122 in `tern/analyze/default/default_common.py`). `is_equal` "performs a deep comparison between two objects by iterating over the dictionary for each object returned by to_dict and comparing the vales for each key in both. This function will only return true if every key value pair matches between the two dictionaries".

To debug, I compared the package metadata dictionaries of the master list package object (from the base layer cache) and the layer package object (from second layer cache) for one of the problem packages, `bsdutils`, and the difference is not clear to me (they appear identical to the human eye). Here's the diff it gives me between the bsdutils package metadata dictionary from the base layer master list (-) and the bsdutils package metadata dictionary from the second layer(+).

```
-{'name': 'bsdutils', 'version': '1:2.25.2-6', 'pkg_license': '', 'copyright': '\nFormat: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/\nUpstream-Name: util-linux\nUpstream-Contact: util-linux@vger.kernel.org\nSource: https://www.kernel.org/pub/linux/utils/util-linux/\n\nFiles: *\nCopyright:      Michal Luscon <mluscon@redhat.com>\n           1986 Gary S. Brown\n           1990 Gordon Irlam (gordoni@cs.ua.oz.au)\n           1991, 1992 Linus Torvalds\n           1991-2004 Miquel van Smoorenburg\n           1992  A. V. Le Blanc (LeBlanc@mcc.ac.uk)\n           1992-1997 Michael K. Johnson, johnsonm@redhat.com\n           1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,\n                 2003, 2004, 2005, 2008 Theodore Ts\'o <tytso@mit.edu>\n           1994 Kevin E. Martin (martin@cs.unc.edu)\n           1994 Salvatore Valente <svalente@mit.edu>\n           1994,1996 Alessandro Rubini (rubini@ipvvis.unipv.it)\n           1994-2005 Jeff Tranter (tranter@pobox.com)\n           1995, 1999, 2000 Andries E. Brouwer <aeb@cwi.nl>\n           1997-2005 Frodo Looijaard <frodo@frodo.looijaard.name>\n           1998 Danek Duvall <duvall@alumni.princeton.edu>\n           1999 Andreas Dilger\n           1999-2002 Transmeta Corporation\n           1999, 2000, 2002-2009, 2010, 2011, 2012, 2014 Red Hat, Inc.\n           2000 Werner Almesberger\n           2004-2006 Michael Holzt, kju -at- fqdn.org\n           2005 Adrian Bunk\n           2007-2014 Karel Zak <kzak@redhat.com>\n           2007, 2011 SuSE LINUX Products GmbH\n           2008 Cai Qian <qcai@redhat.com>\n           2008 Hayden A. James (hayden.james@gmail.com)\n           2008 James Youngman <jay@gnu.org>\n           2008 Roy Peled, the.roy.peled  -at-  gmail.com\n           2009 Mikhail Gusarov <dottedmag@dottedmag.net>\n           2010, 2011, 2012 Davidlohr Bueso <dave@gnu.org>\n           2010 Jason Borden <jborden@bluehost.com>A\n           2010 Hajime Taira <htaira@redhat.com>\n           2010 Masatake Yamato <yamato@redhat.com>\n           2011 IBM Corp.\n           2012 Andy Lutomirski <luto@amacapital.net>\n           2012 Lennart Poettering\n           2012 Sami Kerola <kerolasa@iki.fi>\n           2012 Cody Maloney <cmaloney@theoreticalchaos.com>\n           2012 Werner Fink <werner@suse.de>\n           2013,2014 Ondrej Oprala <ooprala@redhat.com>\nLicense: GPL-2+\n\nFiles: schedutils/ionice.c\nCopyright: 2005 Jens Axboe <jens@axboe.dk>\nLicense: GPL-2\n\nFiles: schedutils/chrt.c\n       schedutils/taskset.c\nCopyright: 2004 Robert Love <rml@tech9.net>\n           2010 Karel Zak <kzak@redhat.com>\nLicense: GPL-2\n\nFiles: disk-utils/raw.c\nCopyright: 1999, 2000, Red Hat Software\nLicense: GPL-2\n\nFiles: sys-utils/nsenter.c\nCopyright: 2012-2013 Eric Biederman <ebiederm@xmission.com>\nLicense: GPL-2\n\nFiles: disk-utils/mkfs.minix.c\n       disk-utils/mkswap.c\nCopyright: 1991, 1992 Linus Torvalds\nLicense: GPL-2\n\nFiles: lib/at.c\n       lib/blkdev.c\n       lib

+{'name': 'bsdutils', 'version': '1:2.25.2-6', 'pkg_license': '', 'copyright': '\nFormat: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/\nUpstream-Name: util-linux\nUpstream-Contact: util-linux@vger.kernel.org\nSource: https://www.kernel.org/pub/linux/utils/util-linux/\n\nFiles: *\nCopyright:      Michal Luscon <mluscon@redhat.com>\n           1986 Gary S. Brown\n           1990 Gordon Irlam (gordoni@cs.ua.oz.au)\n           1991, 1992 Linus Torvalds\n           1991-2004 Miquel van Smoorenburg\n           1992  A. V. Le Blanc (LeBlanc@mcc.ac.uk)\n           1992-1997 Michael K. Johnson, johnsonm@redhat.com\n           1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,\n                 2003, 2004, 2005, 2008 Theodore Ts\'o <tytso@mit.edu>\n           1994 Kevin E. Martin (martin@cs.unc.edu)\n           1994 Salvatore Valente <svalente@mit.edu>\n           1994,1996 Alessandro Rubini (rubini@ipvvis.unipv.it)\n           1994-2005 Jeff Tranter (tranter@pobox.com)\n           1995, 1999, 2000 Andries E. Brouwer <aeb@cwi.nl>\n           1997-2005 Frodo Looijaard <frodo@frodo.looijaard.name>\n           1998 Danek Duvall <duvall@alumni.princeton.edu>\n           1999 Andreas Dilger\n           1999-2002 Transmeta Corporation\n           1999, 2000, 2002-2009, 2010, 2011, 2012, 2014 Red Hat, Inc.\n           2000 Werner Almesberger\n           2004-2006 Michael Holzt, kju -at- fqdn.org\n           2005 Adrian Bunk\n           2007-2014 Karel Zak <kzak@redhat.com>\n           2007, 2011 SuSE LINUX Products GmbH\n           2008 Cai Qian <qcai@redhat.com>\n           2008 Hayden A. James (hayden.james@gmail.com)\n           2008 James Youngman <jay@gnu.org>\n           2008 Roy Peled, the.roy.peled  -at-  gmail.com\n           2009 Mikhail Gusarov <dottedmag@dottedmag.net>\n           2010, 2011, 2012 Davidlohr Bueso <dave@gnu.org>\n           2010 Jason Borden <jborden@bluehost.com>A\n           2010 Hajime Taira <htaira@redhat.com>\n           2010 Masatake Yamato <yamato@redhat.com>\n           2011 IBM Corp.\n           2012 Andy Lutomirski <luto@amacapital.net>\n           2012 Lennart Poettering\n           2012 Sami Kerola <kerolasa@iki.fi>\n           2012 Cody Maloney <cmaloney@theoreticalchaos.com>\n           2012 Werner Fink <werner@suse.de>\n           2013,2014 Ondrej Oprala <ooprala@redhat.com>\nLicense: GPL-2+\n\nFiles: schedutils/ionice.c\nCopyright: 2005 Jens Axboe <jens@axboe.dk>\nLicense: GPL-2\n\nFiles: schedutils/chrt.c\n       schedutils/taskset.c\nCopyright: 2004 Robert Love <rml@tech9.net>\n           2010 Karel Zak <kzak@redhat.com>\nLicense: GPL-2\n\nFiles: disk-utils/raw.c\nCopyright: 1999, 2000, Red Hat Software\nLicense: GPL-2\n\nFiles: sys-utils/nsenter.c\nCopyright: 2012-2013 Eric Biederman <ebiederm@xmission.com>\nLicense: GPL-2\n\nFiles: disk-utils/mkfs.minix.c\n       disk-utils/mkswap.c\nCopyright: 1991, 1992 Linus Torvalds\nLicense: GPL-2\n\nFiles: lib/at.c\n       lib/blkdev.c\n       lib
```

If I use the package name and version to compare packages between layers in `update_master_list()`, the correct output is printed when we load from the cache, so it's clear that the issue lies in the package metadata comparison when pulling from the cache. I suspect something to do with debian non-human readable characters and how they are saved and pulled from the cache for comparison.
```
         # check for whether the package exists on the master list
         exists = False
         for pkg in master_list:
-            if item.is_equal(pkg):
+            if item.name + item.version == pkg.name + pkg.version:
                 exists = True
                 break
         if not exists:

```

@nishak what do you think about using a different check for debian packages in `update_master_list`?

**Comment by nishakm** [comment]
> The reason that a handful of duplicated packages are appearing in the output file when Tern pulls from the cache has to do with a failing `is_equal` check to see if the layer package already exists on the master list in `update_master_list()` (line 122 in `tern/analyze/default/default_common.py`). `is_equal` "performs a deep comparison between two objects by iterating over the dictionary for each object returned by to_dict and comparing the vales for each key in both. This function will only return true if every key value pair matches between the two dictionaries".
> 
> To debug, I compared the package metadata dictionaries of the master list package object and the layer package object (from second layer cache) for one of the problem packages, `bsdutils`, and the difference is not clear to me (they appear identical to the human eye. I uploaded the diff between the bsdutils package metadata dictionary from the base layer master list (-) and the bsdutils package metadata dictionary from the second layer(+) here: [diff.txt](https://github.com/tern-tools/tern/files/6081273/diff.txt)
> 
> If I use the package name and version to compare packages between layers in `update_master_list()`, the correct output is printed when we load from the cache, so it's clear that the issue lies in the package metadata comparison when pulling from the cache in that second layer. I suspect something to do with debian non-human readable characters and differences in how they are saved and pulled from the cache.
> 
> ```
>          # check for whether the package exists on the master list
>          exists = False
>          for pkg in master_list:
> -            if item.is_equal(pkg):
> +            if item.name + item.version == pkg.name + pkg.version:
>                  exists = True
>                  break
>          if not exists:
> ```
> 
> @nishak what do you think?

Excellent sleuthing! The Package class already has a `is_equal` method I think. Why not use that?

**Comment by rnjudge** [comment]
> > @nishak what do you think?
> 
> Excellent sleuthing! The Package class already has a `is_equal` method I think. Why not use that?

Yes, the `Package` `is_equal` method is what's currently broken for debian package dicts when they contain non-human readable characters. Are you saying just edit that function to use a different comparison for debian packages?

**Comment by nishakm** [comment]
> > > @nishak what do you think?
> > 
> > 
> > Excellent sleuthing! The Package class already has a `is_equal` method I think. Why not use that?
> 
> Yes, the `Package` `is_equal` method is what's currently broken for debian package dicts when certain metadata contains non-human readable characters. Are you saying just edit that function to use a different comparison for debian packages?

I can poke at this some more if you'd like.

**Comment by rnjudge** [comment]
Discussed with @nishakm and we will change the `is_equal` method for Package objects to only compare name, version and license.

**Comment by rnjudge** [comment]
The larger issue I am seeing is that the second layer hash is not found in the cache and therefore packages are not loaded from the cache -- this is why Tern does a bunch of additional package comparisons where the Package `is_equal` check fails. In addition, each time I run Tern, the second layer has a different `layer.fs_hash` value so even if the previous hash WAS in the cache, it wouldn't be found.

**Comment by rnjudge** [comment]
The comparison fails because of the debian copyright text comparison issue that we discussed. We can confirm this because if we don't compare the copyrights and only compare name, version and license of the packages in the `is_equal` method, we get the correct output. The master_list gets correctly populated with the first layer packages from the cache. But, since the second layer is not found in the cache, it does a fresh analysis of the second layer and finds more packages there that are also in the base layer. This is expected behavior -- `update_master_list` would typically take care of these duplicates and remove non-unique packages from the second layer but since the copyright texts don't compare properly, the second layer packages are incorrect.

**Comment by nishakm** [comment]
*grumble* Then something is amiss in the JSON parsing of large text.

**Comment by nishakm** [comment]
> _grumble_ Then something is amiss in the JSON parsing of large text.

If that's the case then it's going to be really annoying to fix the parsing. So I think @rnjudge that the quick fix is to skip the copyright comparison like you had suggested.

**Comment by rnjudge** [comment]
@nishakm (final!) update on this: I was wrong about the copyright field being the issue but right about the `is_equal` method being the culprit. The issue is actually with the `pkg_license` field -- when a package has more than one license (as is the case for debian since we use debian-inspector to parse the copyright text), the ordering of the pkg licenses are random and do not compare as ordered lists. Therefore, we need to sort the pkg_license lists before we compare. If we do this, we get the correct output.

```
--- a/tern/classes/package.py
+++ b/tern/classes/package.py
@@ -212,6 +212,11 @@ class Package:
         dictionaries.'''
         other_pkg_dict = other.to_dict()
         for key, value in self.to_dict().items():
+            if key == 'pkg_licenses':
+                # There may be more than one package license. If this is the
+                # case, we need to order pkg_licenses before comparison
+                value.sort()
+                other_pkg_dict[key].sort()
             if value != other_pkg_dict[key]:
                 return False
         return True

```

**Comment by nishakm** [comment]
@rnjudge ship it!
