### ISSUE TITLE
Missing package version

### ISSUE THREAD

**Issue by jcfiorenzano** [tern-tools/tern#902]
Hi I notice that some packages found by tern are found without version, in my case those packages are from a layer that runs npm install, this is the dockerfile
```
FROM node:12.16-alpine
RUN npm install -g serve 
```
Example of a package that doesn't have version:

```
{
          "diff_id": "3063c35ca42be8c1fa62e5088384904c373b2060690a4f9dfc4a77bfef1e253e",
          "fs_hash": "89cd0e9751f294b4714f307a2f5a0556aa23e2368e3233525988fb8c8a55b544",
          "tar_file": "8996d1f6470fbc2886ea502ed165842da1b112961d5b12099b0a91a9883072c2/layer.tar",
          "created_by": "/bin/sh -c npm install -g serve",
          "packages": [
              {
                  "name": "npm",
                  "version": "",
                  "pkg_license": "",
                  "copyright": "",
                  "proj_url": "",
                  "download_url": "",
                  "checksum": "",
                  "origins": [
                      {
                          "origin_str": "npm",
                          "notices": [
                              {
                                  "message": "No metadata for key: version",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: pkg_license",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: copyright",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: proj_url",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: download_url",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: checksum",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: files",
                                  "level": "warning"
                              },
                              {
                                  "message": "No metadata for key: pkg_licenses",
                                  "level": "warning"
                              }
                          ]
                      }
                  ],
                  "files": [],
                  "pkg_licenses": []
              },
```
**Expected behavior**
Package is found with its version.

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version': tern 2.4.0
- Operating System (Linux Distro and version or Mac or Windows): I could reproduce this in Windows 10 20H2 and Ubuntu 20.04
- Python version (3.6 or higher): I could reproduce it with python 3.8.5 and 3.7.9

**Please attach files if they exist**
- report : [tern-report.log](https://github.com/tern-tools/tern/files/6086031/tern-report.log)

**Comment by rnjudge** [comment]
@jcfiorenzano do you know which layer the missing package versions are coming from? The base OS or the second layer? If they are packages installed by `npm` my guess is that the npm package metadata collection/parsing is failing. I see that @JamieMagee opened #903 related to this. Let me give his suggestion a try and see if it resolves the issue you are seeing.

**Comment by jcfiorenzano** [comment]
@rnjudge those components are from the layer, I ran the command just with base image and the components detected have their versions, the only thing that I notice was that in the section files, the files has no version, not sure if that is expected
![image](https://user-images.githubusercontent.com/5582507/110877907-12117400-828f-11eb-8d76-277c30fdd8bd.png)

**Comment by rnjudge** [comment]
@jcfiorenzano I would not expect a file to have a version number.

**Comment by JamieMagee** [comment]
@jcfiorenzano I think this can be closed?
