### ISSUE TITLE
Missing GitPython as a runtime dependency

### ISSUE THREAD

**Issue by JamieMagee** [tern-tools/tern#917]
**Describe the bug**
#897 introduced the use of `GitPython` for all git operations, but it did not add that module as a runtime dependency. When attempting to run tern I receive `ModuleNotFoundError`.

Tests still pass as it is installed as a test dependency.

**To Reproduce**
1. Run any tern command

**Error in terminal**
```
No module named 'git'
  File "/workspaces/tern/tern/analyze/common.py", line 10, in <module>
    import git
  File "/workspaces/tern/tern/analyze/default/container/run.py", line 18, in <module>
    from tern.analyze import common
  File "/workspaces/tern/tern/__main__.py", line 21, in <module>
    from tern.analyze.default.container import run as crun
```

**Expected behavior**
Tern to run

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
- Operating System (Linux Distro and version or Mac or Windows)
- Vagrant file
- Container OS
- Python version (3.6 or higher)
- Cloud environment (AWS, Azure, GCP)

**Please attach files if they exist**

**Comment by rnjudge** [comment]
@JamieMagee This was an oversight on my part as it is a dev dependency but not runtime. I'll get a fix merged for this ASAP.

**Comment by JamieMagee** [comment]
Thanks for the confirmation that it wasn't something on my end 😅 There's no rush, as this isn't in a published release yet, only on `main`.
