### ISSUE TITLE
Unable to identify Distroless version

### ISSUE THREAD

**Issue by JamieMagee** [tern-tools/tern#934]
**Describe the Feature**
Currently tern looks for `PRETTY_NAME` in `/etc/os-release` to figure out the distro we're running on. Normally `PRETTY_NAME` contains both the distribution name and version/release. However, for Distroless `PRETTY_NAME` only contains `Distroless`, and we need to look in `VERSION` or `VERSION_ID` to get the release information.

https://github.com/GoogleContainerTools/distroless/blob/e52e560310a03432eab208f339e73bdfd701a6b6/package_manager/util.py#L36-L57

**Use Cases**
Determining the base Debian version used

**Implementation Changes**
Update the code here to read `VERSION` or `VERSION_ID`

https://github.com/tern-tools/tern/blob/2693eebbe06378d3259d52cf9aa9b0e546ebd938/tern/analyze/default/container/single_layer.py#L30-L55

**Comment by nishakm** [comment]
Looks good! What does the output string look like?

**Comment by JamieMagee** [comment]
This is a sample `/etc/os-release`

```
PRETTY_NAME="Distroless"
NAME="Debian GNU/Linux"
ID="debian"
VERSION_ID="10"
VERSION="Debian GNU/Linux 10 (buster)"
HOME_URL="https://github.com/GoogleContainerTools/distroless"
SUPPORT_URL="https://github.com/GoogleContainerTools/distroless/blob/master/README.md"
BUG_REPORT_URL="https://github.com/GoogleContainerTools/distroless/issues/new"
```

**Comment by rnjudge** [comment]
Let's make sure to test this on other basic OSes, too. I think distroless is an exception to not containing the version in the pretty name. For example, Debian's pretty name is `Ubuntu 18.04.5 LTS`

**Comment by JamieMagee** [comment]
Here's a collection of `/etc/os-release` from various different distributions: https://gitlab.com/zygoon/os-release-zoo. It looks like Distroless is the odd one out.

Should we raise this issue upstream, instead of adding a workaround in tern?

**Comment by rnjudge** [comment]
> Here's a collection of `/etc/os-release` from various different distributions: https://gitlab.com/zygoon/os-release-zoo. It looks like Distroless is the odd one out.
> 
> Should we raise this issue upstream, instead of adding a workaround in tern?

I like this approach! And if we don't get anywhere with that we can add a workaround in Tern as a fallback solution.

**Comment by JamieMagee** [comment]
Okay, let's see how this goes 👀 GoogleContainerTools/distroless#698

**Comment by nishakm** [comment]
Should we close this and reopen it when the above issue gets resolved?

**Comment by rnjudge** [comment]
> Should we close this and reopen it when the above issue gets resolved?

Meh? I would be OK waiting a few more weeks to see if distroless addresses the issue. If they haven't responded to Jamie's ticket by the middle of April, we probably need to implement our own workaround.

**Comment by rnjudge** [comment]
@JamieMagee I don't think this is going to be resolved upstream so we can implement a custom fix in Tern. I think this change could be a good candidate for a "Good first issue", so I will save it for the Grace Hopper Open Source Day we are participating in in a few weeks.

**Comment by JamieMagee** [comment]
Yep, makes sense. Thanks for following up with this!

**Comment by dk-github-acc** [comment]
Hi @rnjudge @nishakm I can take this issue. Can you assign this to me ?
