### ISSUE TITLE
Poor regex performance

### ISSUE THREAD

**Issue by JamieMagee** [tern-tools/tern#939]
**Describe the bug**
When running tern against `postgres:latest` approximately 85% of the runtime is spent in [`update_master_list`](https://github.com/tern-tools/tern/blob/22ef37915152e322cc56d1612fa8777470765744/tern/analyze/default/default_common.py#L122-L145) and approximately 60% of that function (and 50% of total runtime) is spent compiling and running regexes in [`prop_names`](https://github.com/tern-tools/tern/blob/22ef37915152e322cc56d1612fa8777470765744/tern/utils/general.py#L244-L253). 

I've attached profiler logs for more information

**To Reproduce**
1. `tern --driver fuse --clear-cache report --docker-image postgres:latest`
2. Wait...

Profiler logs generated using

```sh
export PYTHONPATH=/workspaces/tern/
pyinstrument -r html -o index.html tern/__main__.py --driver fuse --clear-cache report --docker-image postgres:latest
```

**Expected behavior**
Better performance

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
- Operating System (Linux Distro and version or Mac or Windows)
- Vagrant file
- Container OS
- Python version (3.6 or higher)
- Cloud environment (AWS, Azure, GCP)

**Please attach files if they exist**
- [Profiler logs](https://gist.github.com/JamieMagee/676b47b6d266178eb45ba9d54754fedd)
- ![Screen Shot 2021-03-31 at 16 23 28](https://user-images.githubusercontent.com/1358764/113069190-a70fda80-9174-11eb-9d77-be828f165da9.png)

**Comment by nishakm** [comment]
@JamieMagee are you working on a fix?

**Comment by JamieMagee** [comment]
@nishakm Unfortunately I haven't got time right now to properly investigate and test a fix, but I was looking at this as a starting point:

```py
prop_decorators = r'^__|^_'
for key in obj.__dict__.keys():
    # remove private and protected decorator characters if any
    priv_name = '_' + obj.__class__.__name__
    prop_name = re.sub(priv_name, '', key)
    prop_name = re.sub(prop_decorators, '', prop_name, 1)
    yield key, prop_name
```

to

```py
for key in obj.__dict__.keys():
    prop_name = key.split('__')[-1]
    yield key, prop_name
```

**Comment by nishakm** [comment]
@JamieMagee no worries. I can take a look.

**Comment by nishakm** [comment]
Looks to me like `to_dict()` is called way too many times with `update_master_list`. Let me try looking at that first.
