### ISSUE TITLE
"lock" checks if image exists a second time during analysis

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#951]
**Describe the bug**
When running `tern lock` on a single stage Dockerfile, it looks like it does a check whether the base image exists, which it already did at the beginning of the analysis. I am guessing it does this to get the image digest. It shouldn't have to do this as the image digest is extracted for the base image already at the beginning of the analysis and is stored in the image object.

**Error in terminal**
```
2021-04-19 08:12:41,602 - DEBUG - run - Generating locked Dockerfile...
2021-04-19 08:12:41,603 - WARNING - command_lib - No listing method for 'echo'. Additional analysis may be required.

2021-04-19 08:12:41,607 - WARNING - command_lib - No listing method for 'wget'. Additional analysis may be required.

2021-04-19 08:12:41,607 - WARNING - command_lib - No listing method for 'rm'. Additional analysis may be required.

2021-04-19 08:12:41,608 - WARNING - command_lib - No listing method for 'sed'. Additional analysis may be required.

2021-04-19 08:12:41,631 - DEBUG - docker_api - Checking if image "debian:buster" is available on disk...
2021-04-19 08:12:41,636 - DEBUG - docker_api - Image "debian:buster" found
```

**Expected behavior**
There shouldn't be a check for the image at the end.

**Comment by mukultaneja** [comment]
@nishakm, can I take this bug?

**Comment by nishakm** [comment]
Sure!

**Comment by mukultaneja** [comment]
@nishakm, I looked into the issue and found the [expand_from_images](https://github.com/tern-tools/tern/blob/385301eb2e57ce303efa4e716e18c0a77716c7c1/tern/analyze/default/dockerfile/lock.py#L246) method calls this check [if not img['digest_type'] and not img['digest']](https://github.com/tern-tools/tern/blob/385301eb2e57ce303efa4e716e18c0a77716c7c1/tern/analyze/default/dockerfile/parse.py#L172). I think this check is legitimate with respect to the `lock` use case but just wanted to clarify what could be the impact on other use cases if I remove this check.

On the other hand, the `get_docker_image_digest` method just filling out the image digest and we are ignoring the same information [here](https://github.com/tern-tools/tern/blob/385301eb2e57ce303efa4e716e18c0a77716c7c1/tern/analyze/default/dockerfile/run.py#L177) so maybe we could use this information and get away from removing the above check I mentioned.

need your thoughts here!

**Comment by nishakm** [comment]
> On the other hand, the `get_docker_image_digest` method just filling out the image digest and we are ignoring the same information [here](https://github.com/tern-tools/tern/blob/385301eb2e57ce303efa4e716e18c0a77716c7c1/tern/analyze/default/dockerfile/run.py#L177) so maybe we could use this information and get away from removing the above check I mentioned.
> 
> need your thoughts here!

Yup! This is exactly the problem. A simple way to solve this is to provide a list of `DockerImage` objects to `expand_from_images`. But you will have to come up with a scheme to check which image corresponds to which stage of the Dockerfile. Single stage Dockerfiles are easy to implement this way as the length of the list is just 1. For multiple images, though, there is no way of checking. Maybe DockerImage can have a `stage` property containing the stage number.

**Comment by rnjudge** [comment]
@nishakm @mukultaneja We currently only lock the first stage of the Dockerfile so not sure having a `stage` property makes sense for this particular use case (though it might for others):

```
        else:
            logger.debug('Generating locked Dockerfile...')
            # we can only lock one image for now
            locked_dfobj = lock.lock_dockerfile(dfobj, image_list[0])
            output = lock.create_locked_dockerfile(locked_dfobj)
            lock.write_locked_dockerfile(output, args.output_file)
```

I feel like we should try to store/get the image's sha256 digest in/from the `image_list[0]` object on line 217 of `tern/analyze/default/dockerfile/run.py` and probably pass the object to `create_locked_dockerfile()` somehow so we can pass and set it in `expand_from_images()`. Thoughts?

**Comment by mukultaneja** [comment]
> @nishakm @mukultaneja We currently only lock the first stage of the Dockerfile so not sure having a `stage` property makes sense for this particular use case (though it might for others):
> 
> ```
>         else:
>             logger.debug('Generating locked Dockerfile...')
>             # we can only lock one image for now
>             locked_dfobj = lock.lock_dockerfile(dfobj, image_list[0])
>             output = lock.create_locked_dockerfile(locked_dfobj)
>             lock.write_locked_dockerfile(output, args.output_file)
> ```
> 
> I feel like we should try to store/get the image's sha256 digest in/from the `image_list[0]` object on line 217 of `tern/analyze/default/dockerfile/run.py` and probably pass the object to `create_locked_dockerfile()` somehow so we can pass and set it in `expand_from_images()`. Thoughts?

Agreed, this looks good to me. As I mentioned in my above comment, we could use the ignored `image_info` in the [analyze_single_dockerfile](https://github.com/tern-tools/tern/blob/385301eb2e57ce303efa4e716e18c0a77716c7c1/tern/analyze/default/dockerfile/run.py#L177)  method and fill in the digest for each image, anyway multi_stage is calling up single_stage at the end so I guess it won't make difference. Does it sound good?

**Comment by nishakm** [comment]
@rnjudge We do want to make "lock" work for multistage builds as well. This is why I suggested adding a `stage` property to the `DockerImage` class. If we do, then we can provide `image_list` to `lock_dockerfile` which we could then provide to `expand_from_images`. This also allows us to match stages and stage aliases using the `as` clause in the Dockerfile to the collection of images we analyze. If there is another way to match FROM lines in the Dockerfile to images for each stage, I'm open to suggestions.

**Comment by mukultaneja** [comment]
> @rnjudge We do want to make "lock" work for multistage builds as well. This is why I suggested adding a `stage` property to the `DockerImage` class. If we do, then we can provide `image_list` to `lock_dockerfile` which we could then provide to `expand_from_images`. This also allows us to match stages and stage aliases using the `as` clause in the Dockerfile to the collection of images we analyze. If there is another way to match FROM lines in the Dockerfile to images for each stage, I'm open to suggestions.

@nishakm, I see your point here but I need to understand one thing here, how does this stage property approach would fit right into the current `expand_from_images` implementation? The current implementation looks for the digest of docker image which we do not have because as per the overall flow, we are sending Dockerfile [location](https://github.com/tern-tools/tern/blob/385301eb2e57ce303efa4e716e18c0a77716c7c1/tern/analyze/default/dockerfile/run.py#L122) while creating DockerImage object. That is why the digest is empty at the end for each image here. Should the implementation also need to change or I am missing something here?
