### ISSUE TITLE
Revert #977 after there is a fix for https://github.com/nexB/scancode-toolkit/issues/2529

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#978]
Background:

We are unable to run scancode currently. A fix is in place. Meanwhile, we will fix scancode's dependencies such that it will work with Tern's dockerfile.

**Comment by nishakm** [comment]
@JeroenKnoops @JamieMagee https://github.com/nexB/scancode-toolkit/issues/2529 has been fixed so I will revert the changes to include the frozen dependencies in the Dockerfile :)

**Comment by nishakm** [comment]
Oops! I meant to tag @maxhbr. Sorry!

**Comment by rnjudge** [comment]
@nishakm can we close this?

**Comment by nishakm** [comment]
@rnjudge Not yet. Due to the dependency of the last tern release on an older version of debian-inspector, reverting this change now will break operation again. So we need a new tern release before reverting it.

**Comment by maxhbr** [comment]
> So we need a new tern release before reverting it.

There was a tern release since that comment. ;)

**Comment by rnjudge** [comment]
This has been fixed. Closing.
