### ISSUE TITLE
Support for cyclone dx bom format

### ISSUE THREAD

**Issue by sameer1046** [tern-tools/tern#987]
It would be nice to have the report in Cyclone DX BOM format.

https://github.com/CycloneDX/specification

**Comment by nishakm** [comment]
@rnjudge can we discuss this in the next Tern meeting?

**Comment by rnjudge** [comment]
> @rnjudge can we discuss this in the next Tern meeting?

@nishakm Yes! Meant to bring this up today and totally spaced after the long weekend. Sorry about that. It's on the agenda for next meeting.

**Comment by nishakm** [comment]
Merged #1001. Closing this issue.
