### ISSUE TITLE
Add governance model information

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#990]
**Problem Statement**
Tern has some information about how to contribute to the project but no information about a path to maintainership or general governance. Although this is a small project in its current state, this information would be nice to have in place as a baseline and it can always be updated later. Pulling in @geekygirldawn to see if she has any helpful resources or templates that might help us get started.

**Comment by geekygirldawn** [comment]
This is probably a good template to use as a starting point and then customize for Tern. It's based on the concept of existing maintainers selecting new ones: https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md

The [Contour](https://github.com/projectcontour/community/blob/main/GOVERNANCE.md) governance is a pretty good example, and I like how they do their [MAINTAINERS](https://github.com/projectcontour/community/blob/main/MAINTAINERS.md) files, too :)

This doc on [leadership selection](https://contribute.cncf.io/maintainers/governance/leadership-selection/) and the [Open Source Way](https://www.theopensourceway.org/the_open_source_way-guidebook-2.0.html#_project_and_community_governance) section on governance might also be useful.
