### ISSUE TITLE
Add 'pkg_format' tests to test_class_package.py

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#992]
**Description**
`pkg_format` is a new `Package` property added via https://github.com/tern-tools/tern/commit/b8e7837a045304a1c9553d88636e97de54c28668. Add some tests around this new property. 

**To Do**
Add a test for the `pkg_format` property in the `testIsEqual`, `testToDict`, `testSetters` and `testGetters` functions in `tests/test_class_package.py`.

**Comment by sayantani11** [comment]
Can I contribute to this? For OSD

**Comment by nishakm** [comment]
fixed with #1010
