### ISSUE TITLE
Create a functional test suite for releases

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#995]
**Description**
We need a python script that will invoke all the unit and functional tests in the `/tests` folder. to do pre and post release tests.

**To Do**
1. Look at `ci/test_files_touched.py` from line `37` to line `142`. This is a dictionary of string matches to tests. Note down all unique tests in this dictionary. For example `'tern report -i photon:3.0'` is the first tests and `'python3 setup.py sdist && docker build -t ternd -f ci/Dockerfile . && ./docker_run.sh ternd "report -i golang:alpine"' is the second one. You can report the list of tests in this issue for review.
2. Make a python file named `release_tests.py` in the `ci` folder with this content:
```
# -*- coding: utf-8 -*-                                                         
# SPDX-License-Identifier: BSD-2-Clause

tests = [ <the list of unique tests>]                               
```
3. Submit a PR with this new file.

**Background**
This issue must be merged before anything else relating to #885

**Super Issues**
#885

**Comment by trangology** [comment]
Hi @nishakm, can you assign this issue to me?

**Comment by nishakm** [comment]
> Hi @nishakm, can you assign this issue to me?

I cannot assign the issue, but I will say it is assigned.
